### ISSUE TITLE
How to set quickfix list?

### ISSUE THREAD

**Issue by madskjeldgaard** [stevearc/overseer.nvim#10]
Hi. Thanks a lot for this incredibly cool plugin. I absolutely love it. 

I have defined some templates for working with `platformio` and they work really nicely. The only thing I can't get working is the population of the quickfix list. I cannot deduce from the docs what it is I am doing wrong. Any pointers?

Here's the template:

```lua	
        -- Build
	overseer.register_template({
		name = "piobuild",
		builder = function(params)
			return {
				cmd = {'pio'},
				args = {"run", "--verbose"},
				name = "piobuild",
				cwd = "",
				env = {},
				components = {
					"default",
					"on_result_diagnostics",
					["on_result_diagnostics_quickfix"] = {
						open = true
					}
				},
				metadata = {},
			}
		end,
		desc = "Build a platformio project",
		tags = {overseer.TAG.BUILD},
		params = { },
		priority = 50,
		condition = {
			filetype = {"c", "cpp", "ino", "h", "hpp", "ini"},
			callback = function(search)
				return isdir(search.dir .. "/.pio")
			end
		},
	})
```

**Comment by stevearc** [comment]
This is good feedback; I'll have to adjust the docs to make this clearer. At the moment, setting values in the quickfix relies on having a "diagnostics" field on the result object, which you would typically set using an output parser (see the docs on [parsing output](https://github.com/stevearc/overseer.nvim#parsing-output)). In your example, you're running the command, nothing is parsing the output, then you have two components looking for `diagnostics`, but that value hasn't been set. All this assumes that you want to extract _certain lines_ as build errors, warnings, or similar.

If you instead want to dump _all output_ into the quickfix, have a look at #4. It has a draft API for two ways to accomplish that. Feedback is welcome (encouraged, even). I have been and will be super busy for some weeks (moving and other life events), but I'll be cleaning up that API and merging it as soon as I am able.

**Comment by madskjeldgaard** [comment]
> This is good feedback; I'll have to adjust the docs to make this clearer. At the moment, setting values in the quickfix relies on having a "diagnostics" field on the result object, which you would typically set using an output parser (see the docs on [parsing output](https://github.com/stevearc/overseer.nvim#parsing-output)). In your example, you're running the command, nothing is parsing the output, then you have two components looking for `diagnostics`, but that value hasn't been set. All this assumes that you want to extract _certain lines_ as build errors, warnings, or similar.
> 
> If you instead want to dump _all output_ into the quickfix, have a look at #4. It has a draft API for two ways to accomplish that. Feedback is welcome (encouraged, even). I have been and will be super busy for some weeks (moving and other life events), but I'll be cleaning up that API and merging it as soon as I am able.

Thanks a lot Steve! With your inspiration I managed to do what I wanted to do (which is an amazing thing to be able to do!!!!).
 
For posterity:

```lua
overseer.register_template({
		name = "piobuild",
		builder = function(params)
			return {
				cmd = {'pio'},
				args = {"run", "--verbose"},
				name = "piobuild",
				cwd = "",
				env = {},
				components = {
					"default",
					{"on_output_parse", parser = {
						-- Put the parser results into the 'diagnostics' field on the task result
						diagnostics = {
							-- Extract fields using lua patterns
							{
								"extract",
								"^([^%s].+):(%d+):(%d+): (.+)$",
								"filename",
								"lnum",
								"col",
								"text"
							},
						}
					}},
					"on_result_diagnostics",
					{"on_result_diagnostics_quickfix", {
						open = true
					}}
				},
				metadata = {},
			}
		end,
		desc = "Build a platformio project",
		tags = {overseer.TAG.BUILD},
		params = { },
		priority = 50,
		condition = {
			filetype = {"c", "cpp", "ino", "h", "hpp", "ini"},
			callback = function(search)
				return isdir(search.dir .. "/.pio")
			end
		},
	})
```
