### ISSUE TITLE
vscode tasks fail on empty problemMatcher

### ISSUE THREAD

**Issue by Willem-J-an** [stevearc/overseer.nvim#103]
Vs code generally likes to add an empty problemMatcher to indicate there is no problemMatcher applicable. 
``` json
            "problemMatcher": [],
```

This causes issues for this extension; this returns an error for this plugin:
```
[Error] on_output_parse: one of 'parser', 'problem_matcher' is required
```
The task run is successful afterwards, but I imagine this case may not justify an error?

**Comment by stevearc** [comment]
Should be fixed now. Thanks for the report!
