### ISSUE TITLE
Processes do not send output to task terminal until they are finished

### ISSUE THREAD

**Issue by ghillb** [stevearc/overseer.nvim#11]
The stream of output that some tasks produce, while they are running (e.g., terraform apply), is not displayed in a corresponding task terminal. In this example, that means, that the user does not get any feedback from the process until the task is finished.

Is there a possibility to enable this with overseer?

On another note, what do you think about external task runners, e.g., another tmux or kitty tab?

**Comment by stevearc** [comment]
Overseer is just using the normal Neovim terminal. If there's no output in the terminal, that means there's no output from the process (unless there's a bug in libvterm or Neovim). Do you see anything different if you run the command in your shell versus in Neovim `:terminal`?

In general, I don't think that other task runners (internally referred to as "strategy") are a good idea. A lot of the value of overseer is built on top of tightly controlling the running processes and being able to handle the output of those processes. That said, you can create your own strategy that uses *anything* under the hood, as long as it [conforms to the expected interface](https://github.com/stevearc/overseer.nvim/blob/c17a27821396d76d1ac5759ccefaa000f10d534d/lua/overseer/strategy/init.lua#L6-L14).

**Comment by ghillb** [comment]
It was a mistake on my side, I misremembered how the output works, or they changed something recently. So the issue is obsolete.

That strategy part seems interesting, I will take a look. Maybe I should just use a nvim tab instead of a tmux tab, as I like tabs more than splits, for long-running tasks or debug logs that run in the background and only occasionally need a look.

**Comment by stevearc** [comment]
If you're thinking of tabs vs splits, you don't need to make a new strategy. The default terminal strategy runs the task in a terminal buffer, and you can open that wherever you want (tab, split, float, etc). There are already actions for opening the terminal in a split or float, but it would be easy to add another one to open the terminal in a new tab instead.

https://github.com/stevearc/overseer.nvim/blob/c17a27821396d76d1ac5759ccefaa000f10d534d/lua/overseer/task_list/actions.lua#L133-L144

**Comment by ghillb** [comment]
That's pretty neat and yields (with some slight modification) exactly what I want: the task running in a background nvim tab:

```lua
["open tab (background)"] = {
  desc = "open terminal in a new tab",
  condition = function(task)
    local bufnr = task:get_bufnr()
    return bufnr and vim.api.nvim_buf_is_valid(bufnr)
  end,
  run = function(task)
    local t = vim.api.nvim_get_current_tabpage()
    vim.cmd([[tabnew]])
    vim.api.nvim_win_set_buf(0, task:get_bufnr())
    vim.api.nvim_set_current_tabpage(t)
  end,
},
```
Thanks!

**Comment by stevearc** [comment]
Great! And in case you didn't find it yet, the [Actions](https://github.com/stevearc/overseer.nvim#actions) section of the README explains how to easily add your own custom actions (as opposed to modifying the overseer source)
