### ISSUE TITLE
`on_output_parse` doesn't get output when use toggleterm

### ISSUE THREAD

**Issue by meijieru** [stevearc/overseer.nvim#113]
When attempting to create a customized parser, I face a problem where the lines I am trying to print from [this location](https://github.com/stevearc/overseer.nvim/blob/979f93c57885739f1141e37542bad808a29f7a9a/lua/overseer/component/on_output_parse.lua#L74) appear to be empty when using toggleterm. However, when I use the terminal strategy, the lines are not empty.

**Comment by stevearc** [comment]
Should be fixed!
