### ISSUE TITLE
Lines in editor window

### ISSUE THREAD

**Issue by sho-87** [stevearc/overseer.nvim#115]
This is pretty minor, but there are some lines in the title of the editor window:

![image](https://user-images.githubusercontent.com/5199715/223512836-882d5b51-884d-4cf6-ad07-4f98670c04c8.png)

Where are they coming from? They seem like indent guides?

**Comment by stevearc** [comment]
Could be. Do you have `indent-blankline.nvim` installed? This could also be `:help listchars`. If you do `:set nolist` do they go away?

**Comment by sho-87** [comment]
they dont go away with `nolist` and yes i do have indent blankline installed. I could just add it to the exclusion list - what is this windows file/buf type?

although I notice that this particular window looks different from other windows/pickers because the title is not in the same line as the top border. would this go away if this was just moved up to the title line? eg

![image](https://user-images.githubusercontent.com/5199715/224607083-84a340cf-39d0-4b63-8466-2acba7f2a0f3.png)

**Comment by stevearc** [comment]
You can find the buffer/filetype yourself with `:set buftype?` and `:set filetype?`

I could pull that line out and create a new floating window to hold the title but...don't really feel like it's worth the effort at the moment.

**Comment by sho-87** [comment]
thats fair. the ft exclusion worked (using ft `OverseerForm`) so will close this
