### ISSUE TITLE
Cargo failed to start task

### ISSUE THREAD

**Issue by sho-87** [stevearc/overseer.nvim#116]
I'm a bit confused about how to use builtin tasks and why they're not working

I created a new cargo project, `:OverseerRun`, I see the builtin cargo templates, but when I run one I get:

```
12:07:40 PM msg_show [ERROR] Strategy 'toggleterm' failed to start for task 'cargo build': Vim:E475: Invalid argument: expected valid directory
```
The same happens even if my strategy is regular terminal instead of toggleterm

Given that the template is able to find the Cargo.toml file, I expect that the tasks already know what the project directory is and I don't need to add/edit anything myself to make this work?

**Comment by sho-87** [comment]
it looks like the cargo_dir being passed to cwd [here](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/template/cargo.lua#L52) gets its path from `get_cargo_dir()`, but `vim.fs.find` is returning the path to the Cargo.toml file, rather than the directory it is in.

changing the function to print the returned path gives:
```
local function get_cargo_dir(opts)
    local path = vim.fs.find("Cargo.toml", { upward = true, type = "file", path = opts.dir })[1]
    print(path)
  return path
end

C:\Users\Simon\test2/Cargo.toml
```

**Comment by sho-87** [comment]
just tested this with an npm project and overseer works fine. looks like the npm template wraps the `vim.fs.find` in a `vim.fs.dirname` to get the directory instead of the file itself?

**Comment by stevearc** [comment]
Exactly right. Sorry, I think this got broken in the migration to use `vim.fs` for all the file finding. Should be fixed now!
