### ISSUE TITLE
No VS Code task provider for 'nil'

### ISSUE THREAD

**Issue by GiuseppeMP** [stevearc/overseer.nvim#118]
Hey guys!

I create a simple `tasks.json` in .vscode directory in the root folder.

```
{
    "tasks": [
        {
            "name": "Echo example",
            "cmd": "echo 'Current file = ${file}'"
        },
    ]
}
```
`:OverseerToggle, Open` are empty.
`:OverseerInfo` returns this message `No VS Code task provider for 'nil' `.

Minimal configuration: `require('overseer').setup()`

<img width="330" alt="image" src="https://user-images.githubusercontent.com/4944009/224556951-66716fef-7381-48cb-86f9-7c9748f225ee.png">

I read the docs, but gotta no clue of I'm missing.

Ty,

**Comment by stevearc** [comment]
This is because you're missing the `type`. You need to have either `"type": "shell"` or `"type": "process"`, according to the [documentation on custom tasks](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks). Also I believe `"name"` is deprecated; they seem to use `"label"` now.

**Comment by GiuseppeMP** [comment]
@stevearc ty! worked with this tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo_example",
            "type": "shell",
            "command": "echo 'Current file = ${file}'"
        }
    ],
    "group": "test",
    "presentation": {
        "reveal": "always",
        "panel": "new"
    }
}
```
Btw, Is possible to store these jsons in the nvim config dir, for common tasks? Instead of .vscode of each directory?

**Comment by stevearc** [comment]
Nope, the `tasks.json` format is currently per-directory, just like how it work in VS Code. If you want general tasks to always be available, you'll have to register them with lua. If you'd really prefer to have general tasks defined this way, I can probably add an API call to load a `tasks.json` file from an arbitrary location

**Comment by GiuseppeMP** [comment]
@stevearc Today is my third day using overseer in my config, I believe I will abandon the `tasks.json`, I enjoyed defining them with lua.
