### ISSUE TITLE
`&&` in tasks.json `args` field

### ISSUE THREAD

**Issue by jyf-111** [stevearc/overseer.nvim#119]
OS: Windows
NVIM: v0.8.3

i try to use `&&` to run two tasks in one toggleterm

tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "g++ build",
            "type": "shell",
            "command": "g++",
            "args": [
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.exe",
                "-g",
                "-Wall",
                "-static-libgcc",
                "-std=c++20",
                "&&",
                "${fileDirname}/${fileBasenameNoExtension}.exe"
            ],
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
---
### overseer surround `&&` with `""` ,thus `&&` put into `g++`
<img width="600" alt="image" src="https://user-images.githubusercontent.com/77335030/227718417-4c34b30d-ed26-4709-a8d2-a47284395c61.png">

### use vscode run the same tasks.json, everyting is ok

<img width="600" alt="image" src="https://user-images.githubusercontent.com/77335030/227718574-8cfff0ae-d2d9-4da9-9f15-fb79af070c8e.png">

---

### can we remove `""` around every item in `args`?

now i can only put every thing in `args` into `command` to solve this question? like below:
```json
"command": "g++ ${file} -o ${fileDirname}/${fileBasenameNoExtension}.exe -g -Wall -static-libgcc -std=c++20 && ${fileDirname}/${fileBasenameNoExtension}.exe",
```
but i still hope to use `args` field. Thanks.

**Comment by stevearc** [comment]
I have overhauled the mechanisms both for quoting and variable interpolation of VS Code tasks. I believe it should work for you now, but I didn't test it on windows. Can you give it a try?

**Comment by jyf-111** [comment]
everything ok on windows.
Thank you for your quick reply

**Comment by jyf-111** [comment]
`command` with `args` run ok

---
emmmmm, still a little bug

this is my tasks.json, i just use `command` field
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "xmake",
            "type": "shell",
            "command": "g++ ${file} -o ${fileDirname}/${fileBasenameNoExtension}.exe -g -Wall -static-libgcc -std=c++20 && ${fileDirname}/${fileBasenameNoExtension}.exe",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
in vscode run correct
but in overseer it seems that the whole command surround with a `""`
<img width="600" alt="image" src="https://user-images.githubusercontent.com/77335030/227785801-7d2323f3-a921-4638-a0be-f2af4b20b64e.png">
the output chinese means the command is not correct

i think just move `""` everything will be ok

**Comment by stevearc** [comment]
Should be fixed now
