### ISSUE TITLE
[feature] exporting task bundles

### ISSUE THREAD

**Issue by kha-dinh** [stevearc/overseer.nvim#122]
I want to share the build tasks with my other team members on a project. Using VSCode tasks, this can be done fairly efficiently. However, tasks built using overseer don't have the same portability. I know bundle files are saved in `~/.local/state/nvim/overseer,` but there is no way to export bundles conveniently. 

Because of this, I think having a conversion layer between overseer bundles and VSCode tasks would be nice. You can create tasks with overseer first, then export them into VSCode tasks later. We already have VSCode  `tasks.json` support, so I guess implementing the reverse direction would be straightforward.

I am new to the plugin, so sorry if I am missing something here.

**Comment by stevearc** [comment]
It would actually be quite difficult and a lot of work to try to convert an arbitrary overseer task to the VSCode format. The best way to share tasks with your team on a project is the VSCode `tasks.json` format, and the best way to create those is unfortunately by hand. The good news is that it shouldn't be that difficult to do and the format/process is pretty well documented.
