### ISSUE TITLE
is_subpath() in lua/overseer/files.lua should be case-insensitive in Windows

### ISSUE THREAD

**Issue by ollbx** [stevearc/overseer.nvim#132]
The function `is_subpath()` in `lua/overseer/files.lua` is case-sensitive in Windows. This causes an issue where `add_template_hook()` does not match the specified directory, unless the case happens to match exactly. Easiest solution is probably something like:

```lua
if M.is_windows then
   root = root:lower()
   candidate = candidate:lower()
end
```

before the return statement.

**Comment by stevearc** [comment]
fixed
