### ISSUE TITLE
OverseerToggle horizontal option

### ISSUE THREAD

**Issue by athanase** [stevearc/overseer.nvim#134]
Hello,

First, this plugin is extremely useful.
I am new to neovim and it's plugin ecosystem, so I might have missed something.
Is there an option to open the Overseer window in an horizontal pane instead of a vertical one ?

**Comment by stevearc** [comment]
This was talked about a bit in #6
Maybe read through that discussion and provide outline of how you imagine it would look? Because for the content being laid out I can't picture how it would work in any way that would make sense.

**Comment by athanase** [comment]
What has been first asked in #6  is exactly what I am trying to achieve.
 ```
+-----------------------------------+
|                  |                |
|      Win1        |      Win2      |
|                  |                |
|                  |                |
+------------------------------------
| Task 1                            |
| Task 2                            |
+-----------------------------------+
```

This would be extremely useful since I can keep an eye at the last line of the output of the tasks, and following the task list status.

**Comment by athanase** [comment]
Also, your suggestion on #6 would be really useful :

_Another possibility would be (more like VS Code) to have some way to open a dedicated window at the bottom of the editor, and any time a new task is started update that window to display the terminal for that task._

Do you plan on adding this to the plugin ?

I have started using it and adding templates for cmake based builds. It really is a breeze to have so much customization.

**Comment by stevearc** [comment]
I've decided to do a hybrid solution of both, so you can open a horizontal split at the bottom that contains both the task list and a preview of the most recent task's output. You can open this view with `:OverseerToggle bottom`. There are some new config options `task_list.min_height`, `task_list.max_height`, and `task_list.height` that you can use to set the default height of the horizontal split view

![image](https://github.com/stevearc/overseer.nvim/assets/506791/da34f4e5-7055-4fe6-a7df-3c815e03d516)

**Comment by athanase** [comment]
This behavior is exactly what I was expecting. 
Awesome work, thank you very much. 

Note: This plugin is really awesome.

**Comment by petobens** [comment]
>  contains both the task list and a preview of the most recent task's output

Hi @stevearc is it possible to add a mapping to scroll the task output from within the task list? (I can open a new issue for this).
