### ISSUE TITLE
`restart_on_save` doesn't work correctly when two files has the same name but different ext.

### ISSUE THREAD

**Issue by nyngwang** [stevearc/overseer.nvim#139]
I have two very similar files one for `c` one for `cpp`. This following one is for `cpp`. Since I have set `paths = { file }`, the `restart_on_save` should only be triggered when this file changed **only**. But if you create two files `hello.c` and `hello.cpp` in the same folder, and then run the config with the setup below for both. Then when you save one of them, it's possible that `restart_on_save` will be triggered for both. This doesn't happen when the two files have different names, e.g. `hello.c` and `hello2.cpp`.

```lua
return {
  cmd = { 'g++' },
  cwd = vim.fn.expand('%:p:h'),
  args = { file },
  components = {
    { 'on_output_quickfix', open = true },
    {
      'restart_on_save',
      -- delay = 500,
      paths = {
        file,
      }
      -- method = 'autocmd',
    },
    'default'
  },
}
```

## DEMO

notes:

1. You can see the filename in the winbar of each window.
2. You can see the compilation log by noice.nvim at the bottom-right corner. In the case of the buggy one, both files are compiled.

### on the same name but different ext. (buggy)

https://github.com/stevearc/overseer.nvim/assets/24765272/cea66b89-a51d-4db1-9235-031dc6fabb4f

### on different names (expected)

https://github.com/stevearc/overseer.nvim/assets/24765272/a886d477-0f4d-42d6-9c1d-dbf3daac4698

**Comment by stevearc** [comment]
Fixed!

**Comment by nyngwang** [comment]
Thank you! (I think GitHub should provide a spaceX rocket emoji for comment)
