### ISSUE TITLE
Add a mapping to scroll task output

### ISSUE THREAD

**Issue by stevearc** [stevearc/overseer.nvim#140]
>  contains both the task list and a preview of the most recent task's output

Hi @stevearc is it possible to add a mapping to scroll the task output from within the task list? (I can open a new issue for this).

_Originally posted by @petobens in https://github.com/stevearc/overseer.nvim/issues/134#issuecomment-1547144782_

**Comment by stevearc** [comment]
Added!

**Comment by petobens** [comment]
Awesome!! Thank you :)
