### ISSUE TITLE
Recent telescope commit breaks vscode tasks (${file} not passed to command)

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/overseer.nvim#144]
Today, `telescope.nvim` had a bunch of major refactoring & update commits. One of these commits completely broke overseer's vscode/tasks.json code running capability.

I have narrowed the offending to this [commit](https://github.com/nvim-telescope/telescope.nvim/commit/3f1b57908b312e7f3bfd919c52c61524a673e622).  From this commit onwards, the `${file}` argument does not get processed by the code runner. All tasks that use `clang`, `gcc` etc are broken and error out by printing `no input file argument`. 

I lack the technical background in `lua` to make a minimal example to demonstrate the issue to the maintainers of telescope. May I request if you could please try to reproduce the problem, and if possible help with a suitable fix?

As a temporary workaround, I have pinned my `lazy` plugin spec for telescope to the last working commit as follows

```
  { "nvim-telescope/telescope.nvim", commit = "066bda8ea44fd981bc15b86730cc36ebc92d9788" }, -- last working commit that works with vscode/tasks.json (overseer.nvim)
```

**Comment by stevearc** [comment]
The fix, assuming you're using `dressing.nvim` and not `telescope-ui-select.nvim` is https://github.com/stevearc/dressing.nvim/commit/f19cbd56f7f8cad212c58a7285d09c5d9c273896

The commit you identified caused the telescope window to delay closing by a minuscule amount. That meant that we got the `vim.ui.select` callback while the cursor was still in the telescope window, so it was trying to resolve the `${file}` and coming up empty. I've added a delay in the dressing.nvim telescope integration and that seems to fix it.

**Comment by G0V1NDS** [comment]
I am still facing this issue intermittently, with dressing.nvim. Even though I am on latest version of dressing. Sometimes the `tasks.json` and `makefile` tasks load and sometimes they don't.

**Comment by stevearc** [comment]
@G0V1NDS it looks like the offending change in telescope was reverted https://github.com/nvim-telescope/telescope.nvim/pull/2538
Have you updated telescope past that revert?

**Comment by G0V1NDS** [comment]
I had everything upto date at that moment. 
I anyways started using `fzf-lua` backend, not facing the issue anymore.
