### ISSUE TITLE
How do I run a file after building?

### ISSUE THREAD

**Issue by lavish440** [stevearc/overseer.nvim#146]
I am trying to compile and run a C++ file using overseer. I copied the example for building C++ from the README. Building is working fine but what I want to do is to compile and run the compiled file in a floating toggleterm window. 
Any help would be highly appreciated.

**Comment by stevearc** [comment]
Two approaches: you could either do `compile && run` using your shell in the same task. That would look like
```lua
cmd = string.format("g++ %s -o a.out && ./a.out", vim.fn.expand("%:p"))
```
This is the equivalent of running `g++ <file>.cpp -o a.out && ./a.out` in your terminal.

The other way to do this would be to separate the "run" and "compile" tasks. The "run" task would add a dependency to the "compile" task using the [dependencies component](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md#dependencies). That might look something like this:
```lua
-- Note: this is untested so it may require some fiddling
{
  name = "g++ build and run",
  builder = function()
    -- Full path to current file (see :help expand())
    local file = vim.fn.expand("%:p")
    local outfile = vim.fn.expand("%:p:r") .. ".out"
    return {
      cmd = { outfile },
      components = {
        -- Note that since we're using the "raw task parameters" format for the dependency,
        -- we don't have to define a separate build task.
        { "dependencies", task_name = { { cmd = "g++", args = { file, "-o", outfile } } } },
        { "on_output_quickfix", open = true },
        "default"
        },
    }
  end,
  condition = {
    filetype = { "cpp" },
  },
}
```

**Comment by lavish440** [comment]
@stevearc Thanks a lot
Also how do I get the output of the above compilation in the floating terminal inside Neovim?

**Comment by stevearc** [comment]
You can use the toggleterm strategy to run your tasks. You can see the documentation for that [here](https://github.com/stevearc/overseer.nvim/blob/master/doc/third_party.md#toggleterm). There are a bunch of options that allow you to customize when the terminal is opened/closed and some other behavior.

**Comment by lavish440** [comment]
Getting the following errors when using the above specified config
```
Error executing vim.schedule lua callback: ...cker/start/overseer.nvim/lua/overseer/component/init.lua:212: Component 'dependencies' requires param 'task_names'
stack traceback:
        [C]: in function 'error'
        ...cker/start/overseer.nvim/lua/overseer/component/init.lua:212: in function 'validate_params'
        ...cker/start/overseer.nvim/lua/overseer/component/init.lua:253: in function 'instantiate'
        ...cker/start/overseer.nvim/lua/overseer/component/init.lua:293: in function 'load'
        ...te/pack/packer/start/overseer.nvim/lua/overseer/task.lua:252: in function 'add_components'
        ...te/pack/packer/start/overseer.nvim/lua/overseer/task.lua:115: in function 'new_uninitialized'
        ...te/pack/packer/start/overseer.nvim/lua/overseer/task.lua:123: in function 'new'
        ...acker/start/overseer.nvim/lua/overseer/template/init.lua:252: in function 'build_task'
        ...acker/start/overseer.nvim/lua/overseer/template/init.lua:366: in function 'build'
        ...ack/packer/start/overseer.nvim/lua/overseer/commands.lua:290: in function 'handle_tmpl'
        ...ack/packer/start/overseer.nvim/lua/overseer/commands.lua:323: in function 'on_choice'
        .../packer/start/dressing.nvim/lua/dressing/select/init.lua:78: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by lavish440** [comment]
Changed the task_name to task_names and it is not giving any errors but still I'm unable to get the file to run at all. Also despite using the toggleterm strategy, I'm not still getting the output  in the Terminal.

**Comment by lavish440** [comment]
Got the toggleterm working by using `strategy = "toggleterm",` but when the program tries to give me some output, it fails
```
[ERROR] Task /home/lavish/College/Projects/C++/factors dispatch on_output_quickfix.on_output_lines: ...rseer.nvim/lu
a/overseer/component/on_output_quickfix.lua:30: Invalid window id: 1009
```

**Comment by lavish440** [comment]
Solved the issue by changing `{ "on_output_quickfix", open = true },`  to `{ "on_output_quickfix", open = false },`

**Comment by lavish440** [comment]
Everything is working as expected but I am still having a small problem. After executing the task,  the output is successfully shown in the toggleterm window but after the execution completes, the toggleterm window remains opened but gets unfocused and displays `[Process exited 0]`. After focusing the window, I'm unable to close it using my usual toggleterm keybinds. The only way to close it is going into Insert mode and pressing enter.

**Comment by stevearc** [comment]
This is because overseer doesn't have perfect integration with toggleterm. There are a few operations (like the `open...` actions) that operate directly on the underlying terminal buffers instead of using toggleterm windows. See the discussion on #159 for more details and a link to a potential workaround. I have some ideas for improving this, but no estimate for when I'll be able to get to it.
