### ISSUE TITLE
Dispatch ":Make" recipe unexpected results

### ISSUE THREAD

**Issue by pianocomposer321** [stevearc/overseer.nvim#151]
Hello, thanks for the plugin!

Obviously it's only meant to be a short example, but just thought I'd let you know that the vim-dispatch-like `:Make` command in the docs/recipes.md has a couple issues. It doesn't respect the argument placeholder (`$*`, see `:help makeprg`), and it doesn't properly set the errorformat.

Here's my modified version of the code, maybe it will be helpful:

```lua
vim.api.nvim_create_user_command("Make", function(params)
  local cmd_split = vim.split(vim.o.makeprg, "%s+", {})
  local args = params.fargs
                                                                                                  
  local front, back
  for ind, arg in ipairs(cmd_split) do
    if arg == "$*" then
      front = vim.list_slice(cmd_split, 1, ind - 1)
      back = vim.list_slice(cmd_split, ind + 1, #cmd_split)
      cmd_split = front
      args = {unpack(params.fargs), unpack(back)}
      break
    end
  end
                                                                                                  
  local task = require("overseer").new_task({
    cmd = cmd_split,
    args = args,
    components = {
      { "on_output_quickfix", errorformat = vim.o.efm, open = not params.bang, open_height = 8 },
      "default",
    },
  })
  task:start()
end, {
  desc = "",
  nargs = "*",
  bang = true,
})
```

**Comment by stevearc** [comment]
Good catch! Would the method used in [the :Grep recipe](https://github.com/stevearc/overseer.nvim/blob/master/doc/recipes.md#asynchronous-grep-command) work? The thing I would worry about with this solution is proper handling of quoted args and spaces

```lua
  local args = vim.fn.expandcmd(params.args)
  -- Insert args at the '$*' in the grepprg
  local cmd, num_subs = vim.o.makeprg:gsub("%$%*", args)
  if num_subs == 0 then
    cmd = cmd .. " " .. args
  end
```

**Comment by pianocomposer321** [comment]
Yes that seems to work! :+1: 

It also is much shorter than my version lol. TIL about expandcmd. Thanks again!

**Comment by stevearc** [comment]
Great! I've updated the recipe. Thanks for the report!
