### ISSUE TITLE
Toggleterm close terminal window but don't get rid of terminal buffer

### ISSUE THREAD

**Issue by pianocomposer321** [stevearc/overseer.nvim#152]
Is there a way to have the terminal window close when the task exits, but not get rid of the terminal buffer? close_on_exit gets rid of the buffer, but I want to just close the window (like `:q`). Or, even better, close only if the status code was 0.

Thanks!

**Comment by stevearc** [comment]
It's probably possible! I don't think toggleterm has an API for this specifically, but you could probably update the strategy to detect when the task exists and close any open windows. I don't have the time to do this myself atm, but I would review a PR.

**Comment by pianocomposer321** [comment]
Fixed https://github.com/stevearc/overseer.nvim/pull/155
