### ISSUE TITLE
Question: What's the easiest way to disable all notifications?

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#158]

**Comment by stevearc** [comment]
Check the [setup options](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#setup-options). Under `component_aliases` the `default` is the list of components that are added to all tasks. You can define your own `default` set when you call `overseer.setup()` and remove the component responsible for creating notifications (`on_complete_notify`)

**Comment by Zeioth** [comment]
I would have never guessed on my own. That worked thank you so much.

**Comment by Zeioth** [comment]
Example of setting up overseer with notifications disabled:

``` lua
  {
    "stevearc/overseer.nvim",
    opts = {
      -- By defining our own default overseer components without 
      -- the notification component, we are disabling all overseer notifications.
      component_aliases = { 
      default = {
      { "display_duration", detail_level = 2 },
      "on_output_summarize",
      "on_exit_set_status",
      "on_complete_notify",
      "on_complete_dispose",
      },
      },
    },
  },
```
