### ISSUE TITLE
How do max_width and min_width of a window work ?

### ISSUE THREAD

**Issue by doubleChu** [stevearc/overseer.nvim#16]
I wanted to set width with a default value so I won't have to press '[' to adjust the width of task_list every time.
Then I try to set max_width and min_width of task_list, I found if I set min_width to some value small enough like {10, 0,1}, I open the task_list, its width is the value of max_width.
This confuses me a lit bit, because in the beginning I thought min_width and max_width were used to limit the width when pressing '[' or ']'.
So may I ask which value would be adopted when I just 'OverseerOpen'? Or what is the best way to define a default width for the window like task_list?

**Comment by stevearc** [comment]
Ah, yes the comments/documentation on those is not great. I've added some more explanation so it should hopefully be clearer now. If you want to set a specific default width for the task list, use
```lua
require('overseer').setup({
  task_list = {
    width = 70, -- 70 columns wide
    -- width = 0.2, -- alternatively using a float, this will be 20% of the editor width
  }
})
```
The `min_width` and `max_width` constraints will then be applied after the default width is used. To disable them, you can set `min_width = 0` and `max_width = 0.99`.

**Comment by doubleChu** [comment]
With `width = 0.2`, `min_width = 0` and `max_width = 0.99` now it looks good. :)
