### ISSUE TITLE
problemMatcher won't match $msCompile

### ISSUE THREAD

**Issue by shaksiper** [stevearc/overseer.nvim#160]
Hi,

I have a fairly simple tasks.json

```json
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "...",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
```

but i am getting [ERROR] Could not find problem matcher '$msCompile'
It won't match msCompile even though $msCompile is present in default_patterns.

Am I missing something here?

**Comment by stevearc** [comment]
There is a difference between a "problem matcher" and a "pattern". A "pattern" looks like this
```json
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
```
And defines the regular expression(s) used to parse the output. A "problem matcher" looks like this

```json
      "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceFolder}"],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }
```
It contains the pattern, plus a few other bits of data about how the pattern should be applied. 

`$msCompile` is a pattern, so it's expected that you would have to define it as: 

```json
"problemMatcher": {
  "pattern": "$msCompile"
}
```

However, I've based all of this off of the (admittedly quite poor) documentation and spelunking through the code. If you can show me an example of this working as-is in VS Code, then it's possible that I've missed something.

**Comment by shaksiper** [comment]
Thanks for your respond. Before opening this issue I also tried it that way as well.

```json
			"problemMatcher": {
				"pattern": "$msCompile"
			}
```

I suspected that might be the case but it still gives me "[ERROR] Could not find problem matcher '$msCompile'" error.

**Comment by shaksiper** [comment]
VS Code works fine with 
`"problemMatcher": "$msCompile"`
Actually VS Code creates tasks.json itself in this form, instead of `"pattern" : ...`

**Comment by stevearc** [comment]
Ohhh, I see it now. They have all those default patterns, but then they also set default problem matchers based on those patterns https://github.com/microsoft/vscode/blob/448ec31cb2d4c65a1ca7845b322d61d5d542d8b1/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L1924-L2007

I'll add those to overseer

**Comment by shaksiper** [comment]
Yeah that makes sense.

Thanks a lot for your work :)
