### ISSUE TITLE
Bug: ToggleTerm intergration: cannot use the ToggleTerm command to close the terminal when task exits

### ISSUE THREAD

**Issue by TroySigX** [stevearc/overseer.nvim#166]
After running the `g++ build` command, by default, a terminal of ToggleTerm will appear to display the result. But after the task is done, I cannot use the plugin's `ToggleTerm` command to close the terminal.

**Comment by stevearc** [comment]
This is a duplicate of #159. There is a workaround linked there for now, and I have some work planned that should help with this.
