### ISSUE TITLE
Feature request: show a preview of what the task does

### ISSUE THREAD

**Issue by TroySigX** [stevearc/overseer.nvim#167]
When selecting tasks, sometimes it is understandable that we forget what the task actually does, so having a preview of what it does is much more convenient. For example, when selecting tasks in `fzf-lua` (via `dressing.nvim`), `overseer` only shows the list of command:
![image](https://github.com/stevearc/overseer.nvim/assets/88051085/5df717ad-9a5a-4e4d-9c0a-b56c3d909084)
But what I would like is to have a preview buffer on the right, to show the preview, like this:
![image](https://github.com/stevearc/overseer.nvim/assets/88051085/da0479f1-07e6-4aa4-881c-f6ad17dd08a8)

**Comment by stevearc** [comment]
I would argue that if you don't know what a task does, then it should be given a clearer name. If the name is still insufficient, you can add a `desc = "this is a longer description"` to the task and that will appear as well.

**Comment by TroySigX** [comment]
Yes, but in some cases, like npm, there is no way to provide the description of the task.
