### ISSUE TITLE
Improvement: Give a filetype to the term spawned by OverseerList

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#169]
So we can pin it using stickybuf.

**Comment by Zeioth** [comment]
Also, it would be neat if pressing q on the terminal buffer displayed on `OverseerToggle`, calls `OverseerToggle` again to hide it.

**Comment by stevearc** [comment]
Filetype is the wrong tool for this. Setting the filetype would have a lot of secondary side effects that are undesirable. I've added a buffer-local variable for these terminal buffers that contains the overseer task ID. You can check for its presence with `vim.b.overseer_task`. If it's present for a buffer, that buffer was created by overseer on behalf of a task.
