### ISSUE TITLE
feat: Is it possible to have nice selection menu (like the one summoned by :OverseerRun) for args ?

### ISSUE THREAD

**Issue by Carbone13** [stevearc/overseer.nvim#177]
When you call OverseerRun you are greeted with a telescope selection menu, from which you can choose your action of choice.
Is it possible to have the same menu in order the select a template parameters ?
For my CMake template, I have a parameter to choice build type : 
```
build_type = {
            type = "enum",
            name = "Build type",
            order = 2,
            optional = false,
            default = "release",
            choices = { "debug", "coverage", "release" }
        },
 ```

Could this be displayed with the telescope prompt ?

**Comment by stevearc** [comment]
Because of how the form input works (multiple fields at a time), it's not possible to have a telescope prompt for the build type param. However, if you use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) the possible values should autocomplete for you when you edit that field

**Comment by stevearc** [comment]
We explicitly register a completion source for nvim-cmp in the input form that only triggers for enum fields.
https://github.com/stevearc/overseer.nvim/blob/07970a8328a35edba4587d47efc99eeb37e60236/lua/overseer/form/utils.lua#L326-L341
The same could probably be done for blink. Note that we do also register an omnifunc, so you can always access the enum values by triggering omnicompletion (`<C-x><C-o>`).
