### ISSUE TITLE
bug: parallel tasks conflict with each other

### ISSUE THREAD

**Issue by Willem-J-an** [stevearc/overseer.nvim#180]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-673+g622ae2f53

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

When I run .vscode/tasks.json in parallel, it appears some npm tasks are interfering with each other. 
With below config, I run a backend project and a frontend project, both on separate npm files. The first task should load the package.json file from the /backendfolder. When I run this task it works. If I run the compound task, the backend task fails saying it cannot find the start task. The log file indicates it is working on the wrong package.json file. It appears the working directory configuration is not being picked up properly when running as a compound task.

### Steps To Reproduce

1. nvim -u repro.lua
2. Create file as described below: .vscode/tasks.json, package.json & backend/package.json
3. :OverseerRun, select run all, note that the run backend task will fail
4. :OverseerToggle to see the results
5. :OverseerRun select run backend, it will work

### Expected Behavior

The task should function the same as when running the task by itself. The cwd option should apply and the task should not fail.

### Minimal example file

.vscode/tasks.json
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "run backend",
      "type": "shell",
      "command": "npm",
      "options": { "cwd": "${workspaceFolder}/backend" },
      "args": ["run", "backend"]
    },
    {
      "label": "run frontend",
      "type": "shell",
      "command": "npm",
      "args": [        "run",       "frontend"      ]
    },
    {
      "label": "run all",
      "dependsOn": ["run frontend", "run backend"]
    }
  ]
}
```
package.json
```
{
    "name": "frontend",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "frontend": "echo 'hi'"
    },
    "dependencies": {    },
    "devDependencies": {    }
}
```
backend/package.json
```
{
    "name": "backend",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "backend": "echo 'hi'"
    },
    "dependencies": {    },
    "devDependencies": {    }
}
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

![image](https://github.com/stevearc/overseer.nvim/assets/51120533/44bbb28a-4842-4c12-9739-52939a089a79)

**Comment by stevearc** [comment]
Should be fixed!
