### ISSUE TITLE
bug: components and strategy of orchestrator subtasks not applied

### ISSUE THREAD

**Issue by MoetaYuko** [stevearc/overseer.nvim#182]
### Neovim version (nvim -v)

0.9.1

### Operating system/version

Arch

### Describe the bug

I use the orchestrator strategy to run two subtasks to build and launch a C++ program sequentially. I use the `on_output_quickfix` component to view build errors (if any), and the `toggleterm` strategy to run the compiled program, but they don't work in practice.

### Steps To Reproduce

1. nvim -u repro.lua
2. open an arbitrary cpp file 
3. `:OverseerRun` and choose g++ build and run
4. the program builds and runs, but doesn't automatically open quickfix and terminal

### Expected Behavior

1. quickfix automatically opens if the source file has compile errors
2. terminal automatically opens to run the program if it builds fine

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        templates = { "builtin", "user.cpp" }
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

-- put the following in .repro/config/nvim/lua/overseer/template/user/cpp.lua
local overseer = require("overseer")

local tmpl = {
  params = { cmd = { type = "string" } },
  builder = function(params)
    local file = vim.fn.expand("%:p")
    local file_noext = vim.fn.fnamemodify(file, ":t:r")
    return {
      name = params.cmd .. " build and run",
      strategy = {
        "orchestrator",
        tasks = {
          {
            "shell",
            name = "build",
            cmd = string.format("%s -g -O2 -Wall -lm %s -o %s", params.cmd, file, file_noext),
            components = { { "on_output_quickfix", open = true }, "default" },
          },
          {
            "shell",
            name = "run",
            cmd = "./" .. file_noext,
            strategy = { "toggleterm", direction = "horizontal" },
          },
        },
      },
    }
  end,
}

return {
  generator = function(opts, cb)
    cb({
      overseer.wrap_template(tmpl, { name = "gcc build and run", condition = { filetype = "c" } }, { cmd = "gcc" }),
      overseer.wrap_template(tmpl, { name = "g++ build and run", condition = { filetype = "cpp" } }, { cmd = "g++" }),
    })
  end,
  condition = {
    filetype = { "c", "cpp" },
  },
}
```

**Comment by stevearc** [comment]
The short version is that these right here:
```lua
          {
            "shell",
            name = "run",
            cmd = "./" .. file_noext,
            strategy = { "toggleterm", direction = "horizontal" },
          },
```
these are passing parameters into the built-in "shell" template. This _looks similar_ but is _different from_ the config object that is passed into `new_task()` to create a new task. This is a very understandable confusion, especially because the built-in "shell" template has many params that are the same as what you would pass in to `new_task`.

I should probably think harder about how I can better document this, or modify the API to prevent this sort of confusion, but for right now I've added both `components` and `strategy` to the list of parameters that the "shell" template accepts. With this change, your example appears to work.

**Comment by MoetaYuko** [comment]
Thanks for the update!
