### ISSUE TITLE
Feature request: lua API function to dispose tasks

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#183]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-887+g18062f70d8

### Operating system/version

arch btw

### Describe the bug

If we had a function like `dispose(tasks[])` or `dispose_all()`, it would be possible to stop and clean all tasks in the results panel before running a new task.

### Steps To Reproduce

x

### Expected Behavior

x

### Minimal example file

x

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

My case of use is for [Compiler.nvim](https://github.com/Zeioth/compiler.nvim): When a user `build and run` a solution (several programs at once). Some of them will run on loop some times (clients, and  stuff like that).

Running the solution multiple times would result in a lot of tasks accumulating in running state. For  this scenarios I'd like to create a function `CompilerStop()` to dispose all running tasks.

This would allow users to create a keymapping to do `CompilerStop()` to dispose all, and then `redo the last task` at once when they need to (I already have the redo part).

**Comment by Zeioth** [comment]
Ok this is possible already
```lua
ovs = require("overseer.task_list")
tasks = ovs.list_tasks({ unique = false })
for _, task in pairs(tasks) do
  task.dispose()
end
```

**Comment by stevearc** [comment]
You're correct, you can use the API for this. I would recommend using [`require("overseer").list_tasks()`](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#list_tasksopts) instead of `overseer.task_list`. I guarantee backwards compatibility of the `overseer.` API methods, but there is no such guarantee for submodules.

You can also use `ipairs` instead of `pairs`, because it returns a list-like table.

Lastly, I would also recommend doing [`overseer.run_action(task, "dispose")`](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#run_actiontask-name) instead of calling the method directly, for the same reasons. The methods that are directly on the task have no API compatibility guarantees across versions.

**Comment by Zeioth** [comment]
Ok I've edited my code to remove the references to `overseer.task_list` and `task.dispose`, and now we are directly using `overseer.list_tasks()` and `overseer.run_action(task, "dispose")` instead. Thank you for the suggestions @stevearc !!

I've updated Compiler.nvim
```lua
  cmd("CompilerStop", function()
    vim.notify("SUCCESS - All tasks have been disposed.", "info")
    local overseer = require("overseer")
    tasks = overseer.list_tasks({ unique = false })
    for _, task in ipairs(tasks) do
      overseer.run_action(task, "dispose")
    end
  end, { desc = "Dispose all tasks running in the compiler" })
```

And NormalNvim compiler.nvim status bar component
```
function M.compiler_state(opts)
  local ovs
  local state
  local tasks
  local tasks_by_status
  local spinner = utils.get_spinner("LSPLoading", 1) or { "" }

  return function()
    if is_available "compiler.nvim" and not ovs then
      vim.defer_fn(function()
        ovs = require("overseer")
      end, 100) -- Hotfix: Defer to avoid stack trace on new files.
    end
    if not ovs then return nil end

    tasks = ovs.list_tasks({ unique = false })
    tasks_by_status = ovs.util.tbl_group_by(tasks, "status")

    state = "INACTIVE"
    if tasks_by_status["RUNNING"] then state = "RUNNING" end

    return status_utils.stylize(state == "RUNNING" and (table.concat({
          " ",
          spinner[math.floor(luv.hrtime() / 12e7) % #spinner + 1] or "",
          "compiling" or "",
        }, "")
      ), opts)

  end
end
```
