### ISSUE TITLE
bug: Plugin fails to install on Android Termux

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#189]
### Neovim version (nvim -v)

0.9.0

### Operating system/version

Android termux 0.118.0

### Describe the bug

When installing all my neovim plugins, overseer is the only one to fail with the error

```sh
checkout failed fatal: not a git repository: ../../.git/modules/.github/nvim_doc_tools
fatal: could not reset submodule index
```
![android](https://github.com/stevearc/overseer.nvim/assets/3357792/30ce2442-2371-4f28-9b63-847507e52171)

### Steps To Reproduce

1. On Texmux, install [NormalNvim](https://github.com/NormalNvim/NormalNvim)
2. Open it for the first time, it will install the plugins automatically.
3. Overseer fails with the described error.

### Expected Behavior

Overseer installs correctly.

### Additional context

I initially tough it would be a git version issue, but both on my PC and on termux are up to date `git 2.42.0`

**Comment by Zeioth** [comment]
On a second pass, the plugin seems to works correctly. What fails is updating overser with lazy on Texmux. So the bug is not as critical as I initially thought.

**Comment by Zeioth** [comment]
Actually, It doesn't seem to work
![Screenshot_20230905_185208_Termux](https://github.com/stevearc/overseer.nvim/assets/3357792/83800cd8-2faa-496f-9844-76a4c4844211)

**Comment by stevearc** [comment]
Could you try cleaning the plugin (`x` on the lazy menu) and then reinstalling? It looks like a problem with the git state that should be fixed with a fresh clone

**Comment by Zeioth** [comment]
Good news, I just had to unpin the overseer version. After reinstalling It works as expected!
![Screenshot_20230906_103655_Termux.jpg](https://github.com/stevearc/overseer.nvim/assets/3357792/93362f12-01ba-44bc-b281-90b0802f6f32)
