### ISSUE TITLE
Is it possible to define a task template to run a vim command or some lua code in vim?

### ISSUE THREAD

**Issue by panpansuannai** [stevearc/overseer.nvim#200]
Hi, is there a way to define a task template to not run a shell command but run some lua code in vim? For example when I write
```lua
        local overseer = require('overseer')
        overseer.register_template({
            name = "[Golang] build",
            builder = function(params)
                return {
                    cmd = {
                        "go"
                    },
                    args = {
                        "build",
                        "."
                    },
                }
            end
          })
```
overseer will took the word 'go' directly as a shell command. What should I do if I want a task template run lua code in vim? Thanks for you help.

**Comment by stevearc** [comment]
Overseer doesn't support lua functions or vim commands. It's tied pretty closely to running external commands via `jobstart`, and relies on these tasks running asynchronously. That said, if you were so inclined you could probably get something working by implementing a custom strategy. You can find the definition here

https://github.com/stevearc/overseer.nvim/blob/ed67e917b9dbb431b435d7380f0c4c94e767b229/lua/overseer/strategy/init.lua#L6-L14
