### ISSUE TITLE
bug: editing finished job in shell deletes output

### ISSUE THREAD

**Issue by matu3ba** [stevearc/overseer.nvim#201]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1178+g34a786bc4

### Operating system/version

Linux ASG148 5.15.0-83-generic

### Describe the bug

Execution of a command and accidental appending closes output buffer.

### Steps To Reproduce

1. Define a command to execute and wait for it to finish.
2. :OverseerToggle!
3. `<CR>` with cursor over job
4. Press 4 for open
5. Press a for insertion mode and any key, ie 's'.

### Expected Behavior

The output window should be a read-only shell buffer. (I was silently hoping that you would implement colors via parsing terminal escape codes, but that sounds pretty gnarly and a big effort without a library plus the setup for a fake terminal tty is cumbersome.)

### Minimal example file

Not relevant.

### Minimal init.lua

Not relevant.

**Comment by stevearc** [comment]
Ah, looks like you're on nightly nvim. They made a change recently to cause terminals to auto-exit more aggressively. Try setting the default strategy to `jobstart`

```lua
require("overseer").setup({
  strategy = "jobstart"
})
```

I've been thinking of making this the default strategy, and the changes coming in 0.10 might be the push I need to do it.

**Comment by matu3ba** [comment]
With this config
```lua
if not has_overseer then
  vim.print("no overseer")
  return
end
if not has_overseer_util then
  vim.print("no overseer.util")
  return
end

overseer.setup({
  actions = {
    ["open tab"] = {
      desc = "Open this task in a new tab",
      run = function(task)
        local bufnr = task:get_bufnr()
        if bufnr and vim.api.nvim_buf_is_valid(bufnr) then
          -- naming tabs requires involved statusline-like setup
          -- https://www.reddit.com/r/neovim/comments/pcpxwq/permanent_name_for_tab/
          vim.cmd.tabnew()
          overseer_util.set_term_window_opts()
          vim.api.nvim_win_set_buf(0, task:get_bufnr())
          overseer_util.scroll_to_end(0)
        end
      end,
    },
  },
  opts = {
    component_aliases = {
      default = {
      { "display_duration", detail_level = 2 },
      "on_output_summarize",
      "on_exit_set_status",
      --"on_complete_notify",
      --"on_complete_dispose", -- this should keep the task
      },
      -- Tasks from tasks.json use these components
      default_vscode = {
        "default",
        "on_result_diagnostics",
        "on_result_diagnostics_quickfix",
      },
    },
  },
  strategy = { "jobstart", use_terminal = false },
  templates = { "builtin", "user.cpp_build", "user.run_script" },
})
```
and closing the resulting tab page neovim also closed the underlying buffer somehow and it seems to me that I did still lose the content.

Is there a more ergonomic way to additionally store the content into increasingly numbered output files with a user-specifiable formatting function for the output file, ie something akind to https://github.com/nvim-lua/plenary.nvim/pull/487/files with a user-providable
```lua
M.fmtLog = function(task_name, task_id)
    return string.format("%s/%s%s.log", vim.api.nvim_call_function("stdpath", { "cache" }), "over_", task_name)
end
```

**Comment by stevearc** [comment]
First: it's true that the buffer is just a normal buffer and if you delete it, it's gone. Overseer can't do anything to prevent that from happening. That said, under normal circumstances closing a tab shouldn't delete the buffer. If you're leaving the tab with `:close` or `:quit`, the buffer should remain intact. If you're leaving it with `:bdelete` or `:bwipe`, then that will kill the buffer too. This problem could most likely be solve just by using the proper command to close the tab.

As for a way to store the output to a file, you could use a hook to generate a log file name and use the existing `on_output_write_file` component

```lua
require("overseer").add_template_hook(nil, function(task_defn, util)
  local name = task_defn.cmd
  if type(task_defn.args) == "string" then
    name = name .. " " .. task_defn.args
  elseif type(task_defn.args) == "table" then
    name = name .. " " .. table.concat(task_defn.args, " ")
  end
  local filename = string.format("%s/overseer/%s.log", vim.fn.stdpath("cache"), "over_", name)
  util.add_component(task_defn, { "on_output_write_file", filename = filename })
end)
```

Or you could create your own [custom component](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-components) that handles the file logging.

**Comment by matu3ba** [comment]
> under normal circumstances closing a tab shouldn't delete the buffer

With `:=require("overseer.config")` I get
```
 component_aliases = {
    default = { { "display_duration",
        detail_level = 2
      }, "on_output_summarize", "on_exit_set_status" },
    default_vscode = { "default", "on_result_diagnostics", "on_result_diagnostics_quickfix" }
  },
```

and it still looks like overseer still discards the content if I do not keep the content open in a window. If the option is active, then I would expect that overseer does not have the entry `11: retain`:
```
1: dispose
2: edit
3: ensure                  (restart the task if it fails)
4: open                    (open terminal in the current window)
5: open float              (open terminal in a floating window)
6: open hsplit             (open terminal in a horizontal split)
7: open output in quickfix (open the entire task output in quickfix)
8: open tab                (Open this task in a new tab)
9: open vsplit             (open terminal in a vertical split)
10: restart
11: retain                  (Don't automatically dispose this task after complete)
12: save                    (save the task to a bundle file)
13: watch                   (restart the task when you save a file)
Type number and <Enter> or click with the mouse (q or empty cancels):
```

Aside, I am closing windows with ZQ. 

If I am not opening the content, ie in a tab altogether, then the behavior does not change and all finished (and not in window opened) tasks are dropped.

**Comment by stevearc** [comment]
I'm looking at your dotfiles, and it seems like you still have the unnecessary `opts = {` nesting
https://github.com/matu3ba/dotfiles/blob/52d2e1dd8c27626bb947635b26f3b97f552b58af/.config/nvim/lua/my_over.lua#L56C1-L56C1

What do you see from `:=require("overseer.config").component_aliases`?

**Comment by matu3ba** [comment]
Having this after running t1,t2,t3,t4:
```
FAILURE: t4
out: /home/misterspoon/.cache/zig/o/4a55b6a35fe612899f1e3e85c009c5af/test
────────────────────────────────────────
FAILURE: t3
out: /home/misterspoon/.cache/zig/o/8e15307ade79a0ef094b4efb9e8fede3/test
────────────────────────────────────────
SUCCESS: t2
out: All 1 tests passed.
────────────────────────────────────────
SUCCESS: t1
out: All 1 tests passed.
```
from this simple zig file via `zig test --test-filter t1|t2|t3|t4 runner.zig`:
```zig
test "t1" {
    return;
}
test "t2" {
    return;
}
test "t3" {
    return error.Fail_t3;
}
test "t4" {
    return error.Fail_t4;
}
```

> What do you see from :=require("overseer.config").component_aliases?
```
:=require("overseer.config").component_aliases
{
  default = { { "display_duration",
      detail_level = 2
    }, "on_output_summarize", "on_exit_set_status" },
  default_vscode = { "default", "on_result_diagnostics", "on_result_diagnostics_quickf
ix" }
}
```

Output on selection is
```
1: dispose
2: edit
3: ensure      (restart the task if it fails)
4: open        (open terminal in the current window)
5: open float  (open terminal in a floating window)
6: open hsplit (open terminal in a horizontal split)
7: open tab    (Open this task in a new tab)
8: open vsplit (open terminal in a vertical split)
9: restart
10: save        (save the task to a bundle file)
11: watch       (restart the task when you save a file)
Type number and <Enter> or click with the mouse (q or empty
 cancels):
 ```

Observations
- It looks like autoclose is disabled (not showing the backed file buffers)
- Might be closed upstream issue, but not sure as I dont follow master HEAD closely

Thus closing.

**Comment by matu3ba** [comment]
Post-mortem: I used `ZQ`, which is the same as `:q!`. However, I should have used `:q`, `:clo` or my new keybinding `ZW`.
