### ISSUE TITLE
use case: (re)start task in new tab to use full width for very long log lines.

### ISSUE THREAD

**Issue by matu3ba** [stevearc/overseer.nvim#204]
Justification: Tasks are not accessible via cmd or function, so one has to use `:newtab` +  `:OverseerToggle` + move cursor over task +  `o`  +  `:bonly`.

Sidenode: Having jump markers as 2 digits for the tasks would be nicer. I dont have too much of an opinion (yet) over history view (current) or list of all task in bundle view or list of all loaded tasks with unique names.

**Comment by stevearc** [comment]
This is definitely scriptable either as a [custom action](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#actions) or just by fetching the task with [overseer.list_tasks](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#list_tasksopts) and calling methods on it directly. Here's an example of a custom action using code taken from the [restart action](https://github.com/stevearc/overseer.nvim/blob/6fe36fc338fbeaf35b0f801c25f7f231c431a64b/lua/overseer/task_list/actions.lua#L36-L43) and the [open vsplit action](https://github.com/stevearc/overseer.nvim/blob/6fe36fc338fbeaf35b0f801c25f7f231c431a64b/lua/overseer/task_list/actions.lua#L150-L162)

```lua
local overseer = require("overseer")
overseer.setup({
  actions = {
    ["Restart in tab"] = {
      desc = "Restart this task in a new tab",
      -- Optional function that will determine when this action is available
      condition = function(task)
        return not task:is_pending()
      end,
      run = function(task)
        task:restart(true)
        local bufnr = task:get_bufnr()
        if bufnr and vim.api.nvim_buf_is_valid(bufnr) then
          local util = require("overseer.util")
          vim.cmd.tabnew()
          util.set_term_window_opts()
          vim.api.nvim_win_set_buf(0, task:get_bufnr())
          util.scroll_to_end(0)
        end
      end,
    },
  },
})
```

**Comment by matu3ba** [comment]
Thanks, I use(d) [to decouple show task vs restart task]:
```lua
overseer.setup({
  actions = {
    ["open tab"] = {
      desc = "Open this task in a new tab",
      run = function(task)
        local bufnr = task:get_bufnr()
        if bufnr and vim.api.nvim_buf_is_valid(bufnr) then
          vim.cmd.tabnew()
          overseer_util.set_term_window_opts()
          vim.api.nvim_win_set_buf(0, task:get_bufnr())
          overseer_util.scroll_to_end(0)
        end
      end,
    },
  },
})
```

Closing.

**Comment by stevearc** [comment]
Honestly, I should probably just have a built-in action for opening in a new tab. There are already actions for open current, open float, open vsplit/hsplit. Tab is a natural fit. Added in ff6e5c5342b2ec70e105e1c3fc9841884f02f560
