### ISSUE TITLE
use case: make floating windows on creation of tasks persistent to allow multiple copy-paste actions

### ISSUE THREAD

**Issue by matu3ba** [stevearc/overseer.nvim#205]
For example, I tend to copy paste relative paths, if the action needs to be relative in 2 steps, because I forget about it.

**Comment by stevearc** [comment]
I'm a bit confused because there are no windows created by default when a task starts. Could you clarify which window it is you're talking about, how it's opening, and what you're trying to copy/paste?

**Comment by matu3ba** [comment]
Copy command from in-build shell.
```
:OverseerRunCmd
./cmd with a lot of arguments
```
Ugh, what was my pwd again? let me quickly copy it to unnamed register.
```
gt/click outside of floating window, etc
```
And now the floating window is gone.

**Comment by stevearc** [comment]
I think that this is better solved by creating a custom keymap or command. The task form is a modal and really does need to behave like a modal. If you find yourself frequently wanting to take a command and re-run it as a task, you could do something like this:
```lua
vim.api.nvim_create_user_command("RunAsTask", function(params)
  local bufname = vim.api.nvim_buf_get_name(0)
  local cmd = params.args
  -- If no args, use the last yanked text as the command
  if cmd == "" then
    cmd = vim.fn.getreg("")
  end
  -- If we're in a terminal, use the cwd of the terminal
  local cwd
  if vim.startswith(bufname, "term://") then
    cwd = vim.fn.expand(vim.split(bufname, "//", { plain = true })[2])
  end
  require("overseer").run_template({ name = "shell", params = { cmd = cmd }, cwd = cwd })
end, { args = "*" })
```

**Comment by matu3ba** [comment]
Thanks for the workaround. Closing as intentional design decision.
