### ISSUE TITLE
custom `.vscode` path

### ISSUE THREAD

**Issue by UTFeight** [stevearc/overseer.nvim#206]
Using `.vscode` as a literal path could not be the way we want to store our tasks.

Some may want to use a custom directory:

```lua
require('overseer').setup {
    dir = "~/.tasks"
}
```

Or just use another path than `.vscode`
```lua
require('overseer').setup {
    dir = ".tasks"
}
```

**Comment by stevearc** [comment]
If you want to use VS Code style tasks, you'll need to put them in `.vscode/tasks.json`. If you want to define your tasks some other way (e.g. [with exrc](https://github.com/stevearc/overseer.nvim/blob/master/doc/recipes.md#directory-local-tasks-with-exrc)) you can put them somewhere else. I don't think there's value to adding config options to load standard task formats from a non-standard location. Hard-coding the location for these types of files is a common practice, see `:help editorconfig` and `:help exrc`.
