### ISSUE TITLE
bug: failed to parse preLaunchTask

### ISSUE THREAD

**Issue by MariaSolOs** [stevearc/overseer.nvim#211]
### Neovim version (nvim -v)

v0.10.0-dev-1260+g9ce162383

### Operating system/version

macOS Sonoma 14.0

### Describe the bug

When using a DAP configuration from a `launch.json` file that has a `preLaunchTask`, the following errors are displayed:
<img width="1512" alt="image" src="https://github.com/stevearc/overseer.nvim/assets/62502207/edb222fd-254c-45e4-b910-2ca2cedff36c">

### Steps To Reproduce

1. Clone [`TypeScript`](https://github.com/microsoft/TypeScript).
2. Rename `.vscode/launch.template.json` to `.vscode/launch.json`.
3. Configure Neovim using the provided settings below.
4. Open any file inside `tests/cases/fourslash`.
5. Press F5 to start the debugger and select the "Mocha Tests (currently opened test)" configuration.

### Expected Behavior

For the `launch.json` (and its corresponding `preLaunchTask`) to successfully execute.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
  { 
    "mfussenegger/nvim-dap",
    keys = {
      {
        "<F5>",
        function() require("dap").continue() end
      }
    },
    dependencies = {
      { 
        "mxsdev/nvim-dap-vscode-js",
        opts = {
          debugger_path = vim.fn.stdpath 'data' .. '/lazy/vscode-js-debug',
          adapters = { "pwa-node", "pwa-chrome", "node-terminal", "pwa-extensionHost" },
        },
      },
      {
        "microsoft/vscode-js-debug",
        build = "npm i && npm run compile vsDebugServerBundle && mv -f dist out",
      },
   },
   config = function()
     local dap = require "dap"
     require("dap.ext.vscode").json_decode = require('overseer.json').decode
     pcall(require("dap.ext.vscode").load_launchjs, nil, {
       node = { "typescript", "javascript" },
     })
   end
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I wasn't able to get DAP working with the repro file (kept giving me `No configuration found for `typescript`.`), but I believe I've fixed the issue with running the tasks

**Comment by MariaSolOs** [comment]
> I wasn't able to get DAP working with the repro file (kept giving me `No configuration found for `typescript`.`), but I believe I've fixed the issue with running the tasks

Oops my bad! I had not realized that I had missed the important part about modifying the launch type from `node` to `pwa-node` 🤦🏻‍♀️ 

I just tried the latest commits though and your fix worked! Thanks a lot <3
