### ISSUE TITLE
Support detection of linked justfile files

### ISSUE THREAD

**Issue by tissieres** [stevearc/overseer.nvim#219]
Hello,
Since my justfile is linked from my `.dotfiles` directory, it is not detected because of the `type = "file"` in this line. In order to support files and links, this filter should be removed. Would you be ok if I submit a PR for this?

https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/template/just.lua#L10

**Comment by stevearc** [comment]
Sure!
