### ISSUE TITLE
Add support for just

### ISSUE THREAD

**Issue by Shatur** [stevearc/overseer.nvim#22]
[Just](https://github.com/casey/just) is a nice general-purpose task runner. Since Overseer supports makefiles it would be great to support just too.

**Comment by stevearc** [comment]
I started looking into Just a while ago but got sidetracked before completion. I'll leave this open to track the progress and come back to it when I get a chance

**Comment by stevearc** [comment]
Support added! Should show up automatically in `:OverseerRun` now.

**Comment by Shatur** [comment]
Thanks!
