### ISSUE TITLE
Why did I get an error "could not read Username for 'https://github.com': terminal prompts disabled" when I install it?

### ISSUE THREAD

**Issue by nullptr-yxw** [stevearc/overseer.nvim#233]
I want to install the plugin by lazy.nvim, but I got the error: `could not read Username for 'https://github.com': terminal prompts disabled`, just like this:

![f26357104340574cc30e63f35938596d](https://github.com/stevearc/overseer.nvim/assets/96286337/194eaaef-fb65-4d48-9ae7-fbef3341d626)

Yet my other plugins can be downloaded normally.

My configuration is:
```lua
return {
    "stevearc/overseer",
    config = function () 
        
    end,
}
```

**Comment by stevearc** [comment]
Sometimes there are git failures. Try cleaning the plugin (with `x`) and reinstalling. This isn't an issue with the plugin

**Comment by nullptr-yxw** [comment]
> Sometimes there are git failures. Try cleaning the plugin (with `x`) and reinstalling. This isn't an issue with the plugin

Uh, maybe I could solve the problem simply by specifing `stevearc/overseer.nvim` instead of `stevearc/overseer`.
Thanks for your answer and awesome plugin very much.
