### ISSUE TITLE
Better conditional callback for cargo builtins

### ISSUE THREAD

**Issue by dzfrias** [stevearc/overseer.nvim#24]
Currently, the template generator checks for a `Cargo.toml` in the current directory. This doesn't allow the user to dispatch `cargo` commands when editing files in directories like `src/`. This could be pretty easily implemented with a `vim.fn.findfile()`, or it could have a more robust implementation. I'd be happy to work on a PR for this!

**Comment by stevearc** [comment]
I would happily review a PR for this!
