### ISSUE TITLE
feature request: wrong package.json picked up in certain project configurations

### ISSUE THREAD

**Issue by emmanueltouzery** [stevearc/overseer.nvim#242]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I've just tried upgrading from a very old version of overseer that was taking the current folder into account to operate, instead of the new setup which is to take into account the current file's folder.

It causes an issue with projects having multiple `package.json` files.

### Provide background

Some projects have package.json files in subfolders, which are not the main project package.json file but rather some submodule marker. This seems prevalent in react-native projects. See this for instance:
https://stackoverflow.com/questions/51701191/react-native-has-something-to-use-local-folders-as-package-name-what-is-it-ca

I work on such a project. So overseer picks up that package.json in the subfolder, and not the main package.json at the root of project, which is the one containing the important tasks.

It would be nice if overseer could auto-detect that this package.json is not the real one... Or alternatively (and maybe this is already possible) if there was a not-too-verbose way for the user to give overseer the path to take into account to find the package.json, or something like that.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I think that the best solution would be to change the task provider to work for multiple `package.json` files. It should search starting from the path of the current file terminating at either the first package.json or the current working directory, whichever comes second. I don't think this would be too terribly difficult of a change
