### ISSUE TITLE
bug: templates without condition field will always match, even if tags don't match

### ISSUE THREAD

**Issue by tobias-haenel** [stevearc/overseer.nvim#252]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

ArchLinux (Linux 6.6.8)

### Describe the bug

Trying to run templates with a matching set of tags, will also display templates without condition fields, even if their tags don't overlap with the searched tags.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. register several task templates without a `condition` field and with different tags (e.g. `tags = {"a"} / {"b"}`) with
```lua
require("overseer").register_template
```
2. Run
```lua
require("overseer").run_template{tags={"a"}, first=false)
```
3. Check the returned templates

### Expected Behavior

A template should only be displayed for selection when its tags overlap with the searched tags.

### Additional context

Proposed fix: remove line 62 to 64 in `condition_matches` and default initialise `condition` with an empty table or default initialise all template condition fields with an empty table https://github.com/stevearc/overseer.nvim/blob/78e893394cef6efee05f31bd65f6dff08b0bac09/lua/overseer/template/init.lua#L61-L113

**Comment by stevearc** [comment]
Should be fixed!
