### ISSUE TITLE
task path for AstroNVim

### ISSUE THREAD

**Issue by pda-gb** [stevearc/overseer.nvim#254]
### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

MacOS 14.2.1

### Describe the bug

No way to specify a path for custom tasks. The settings area for the user is in `~/.config/nvim/lua/user/`. The plugin configuration file will be in `~/.config/nvim/lua/user/plugins/`. But the plugin is looking in `~/.config/nvim/lua/` + `overseer/template/`.  Nothing can be added to the `~/.config/nvim/lua/` folder in astronvim.
How can I specify the full path for tasks?

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

- install AstroNVim
- create userconfig (https://docs.astronvim.com/configuration/manage_user_config/)
- create config ~/.config/nvim/lua/user/plugins/overseer.lua:

```
return {
  'stevearc/overseer.nvim',
    opts = {
    templates = { "builtin", "kt_build" },
    },
  
  load_template = { "kt_build" },
  
  priority = 1000,
  event = "LspAttach",
}
```

The task `kt_build.lua` was created in paths:
~/.config/nvim/lua/user/
~/.config/nvim/lua/user/overseer/template/
~/.config/nvim/lua/user/plugins/ 
~/.config/nvim/lua/user/plugins/overseer/template/

### Expected Behavior

I run the `:OverseerRun` command and see a menu with the kt_build task.

result:
![Screenshot 2024-01-07 at 15 29 54](https://github.com/stevearc/overseer.nvim/assets/52175155/7706cabb-05bf-4cf5-83e0-4e627b15be2e)

**Comment by stevearc** [comment]
There's no way to change the root directory where overseer is looking for templates. If you want to define them in a custom location, you can do that but you will need to manually register them with overseer https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-tasks

```lua
require("overseer").register_template(require("user.overseer.template.kt_build"))
```

One note is that when registered directly like this, you will need to ensure that the template definition includes a `name` (since it won't be auto-created from the module path). You should get a clear error message if you forget, though

**Comment by pda-gb** [comment]
How to add `register_template` to Lazy config `~/.config/nvim/lua/user/plugin/overseer.lua`:

```
return {
  'stevearc/overseer.nvim',
    opts = {
    templates = { "builtin", "kt_build" },
    },
  
  load_template = { "kt_build" },
  
  priority = 1000,
  event = "LspAttach",
}
```

for template `~/.config/nvim/lua/user/overseer/template/kt_build.lua` ?

**Comment by stevearc** [comment]
Try
```lua
return {
  'stevearc/overseer.nvim',
  opts = {
    templates = { "builtin", "kt_build" },
  },
  config = function(_, opts)
    local overseer = require("overseer")
    overseer.setup(opts)
    overseer.register_template(require("user.overseer.template.kt_build"))
  end,
  event = "LspAttach",
}
```

**Comment by pda-gb** [comment]
Yes it works, thank you.
But:
1. The task does not start. I pressed start forcibly through the menu and the task is in PENDING status.
If I select edit from the menu and immediately press enter (without changing anything), the task will start.
![Screenshot 2024-01-10 at 12 19 42](https://github.com/stevearc/overseer.nvim/assets/52175155/00cff8fd-2bc2-4bde-9399-6056be308f4f)

2. The task created through this template has a name in the form of a command, but in the template directly prescribed name through the field "name" (`name = "Kotlin build (gradlew)"`).
![Screenshot 2024-01-10 at 12 39 16](https://github.com/stevearc/overseer.nvim/assets/52175155/bff9920c-aa00-44ea-bcb5-add91b469f47)
Am I not launching tasks correctly?



My config:



<details><summary>~/.config/nvim/lua/user/plugin/overseer.lua</summary>
<p>

```lua
return {
  'stevearc/overseer.nvim',
  opts = {
    -- templates = { "builtin", "user.overseer.template.kt_build(gradlew)" },
  },4

  config = function(_, opts)
    local overseer = require("overseer")
    overseer.setup(opts)
    overseer.register_template(require("user.overseer.template.kt_build(gradlew)"))
    overseer.register_template(require("user.overseer.template.py_run"))
  end,
  
  -- load_template = { "user.overseer.template.kt_build(gradlew)" },

  keys = {
    { "<leader>rr", "<cmd>:OverseerRun<cr>", desc="Run task..." },
    {"<leader>rt", "<cmd>:OverseerToggle<cr>", desc = "Open/Close overseer window"},
    {"<leader>r", name = "qwe", desc = "Build/Run tasks" },
    -- { "<leader>", "<cmd><cr>", desc="" },2
    -- { "<leader>", "<cmd><cr>", desc="" },2
    -- { "<leader>", "<cmd><cr>", desc="" },
  },
  
  priority = 1000,
  event = "LspAttach",
}
``` 

</p>
</details> 


<details><summary>~/.config/nvim/lua/user/overseer/template/kt_build(gradlew).lua</summary>
<p>

```lua

return {
  name = "Kotlin build (gradlew)",
  builder = function()
  -- local file = vim.fn.expand("%:p")
  return {
      cmd = { "./gradlew build" },
      -- args = { file },
      components = { "default" },
    }
  end,
  condition = {
    filetipe = { "kt" },
  },
}

``` 

</p>
</details>

**Comment by pda-gb** [comment]
I think I've found the reason why the task won't start:
[DEBUG] Starting task ./gradlew build
[ERROR] Strategy 'terminal' failed to start for task './gradlew build': Vim:E475: Invalid value for argument cmd: './gradlew build' is not executable

But why is it renamed and started when "editing" ?

**Comment by pda-gb** [comment]
I found a bug in the task run, it's working now.

`~/.config/nvim/lua/user/overseer/template/kt_build(gradlew).lua`

```lua
return {
  name = "Kotlin build (gradlew)",
  builder = function()
  -- local file = vim.fn.expand("%:p")
  local root_project_path = vim.fn.getcwd()
  return {
      cmd = { root_project_path .. "/gradlew", "build" },
      -- args = { file },
      components = { "default" },
    }
  end,
  condition = {
    filetipe = { "kt" },
  },
}

```
