### ISSUE TITLE
feature request: Hidden vscode tasks

### ISSUE THREAD

**Issue by lnc3l0t** [stevearc/overseer.nvim#269]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like an option to hide certain tasks from the OverseerRun list.
I recall it was available in VSCode, but I didn't find the flag in the `tasks.json` [schema](https://vscode-docs.readthedocs.io/en/latest/editor/tasks_appendix/#schema-for-tasksjson).
Shouldn't be too hard to add I imagine, if the feature could be accepted by the author I would like to contribute to this awesome plugin and draft a PR, but I thought to ask for an opinion before attempting.

### Provide background

I tried enabling "hide", "hidden" flag to a task
```json
        {
            "label": "compile",
            "type": "shell",
            "command": "${CC} -O3 -o ${OUT}/main src/${input:file}.c @compile_flags.txt",
            "problemMatcher": "$gcc",
            "hide": true
        },
```
but it still shows up in the run menu

### What is the significance of this feature?

strongly desired

### Additional details

Thank you for your plugin!

**Comment by stevearc** [comment]
I would be open to adding this, but only if it is actually part of the `tasks.json` spec. I don't want to add custom functionality separate from the VSCode implementation. That said, the spec in their documentation is _woefully_ incomplete; I've had to dig through their code many times to figure out how things are actually expected to work. If you can find proof of this feature I would love to add it to overseer.
