### ISSUE TITLE
bug: Orchestrator strategy undefined behavior

### ISSUE THREAD

**Issue by Timur-ux** [stevearc/overseer.nvim#273]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11 WSL 2(Ubuntu 22.04)

### Describe the bug

I want to setup sequence of tasks to compile .tex project
There are 3 tasks:
1. latex
2. dvips
3. ps2pdf

In guides.md I read use orchestrator strategy for this purpose, but when I start task I got
Strategy 'orchestrator' failed to start for task 'latex(shell-escape) + dvips + ps2pdf': vim/shared.lua:0: s: expected string, got nil

From error message I only can suggest that my task config don't have some string field but really have no idea what concrete. 

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

1. Configure overseer as I wrote below

### Expected Behavior

Successfully complete sequence of 3 commands

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  {                                                                                                                                                
    'stevearc/overseer.nvim'
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

require("overseer").setup({
  log = {
    {
      type = "file",
      filename = "overseer.log",
      level = vim.log.levels.DEBUG, -- or TRACE for max verbosity
    },
  },
  templates = {
    "builtin",
    'tex.latex(shell_esc)_dvips_ps2pdf'
  },
})

-- in overseer.template.tex.latex(shell_esc)_dvips_ps2pdf.lua
local tasks = {
    {
      name = "latex(shell_esc)",
      cmd = {'latex'},
      args = {
        '-shell-escape',
        vim.fn.expand('%:p:h') .. '/' .. vim.fn.expand('%:r') .. '.tex'
      }
    },
  {
    name = "dvips",
    cmd = { "dvips" },
    args = {
      vim.fn.expand("%:p:h") .. "/" .. vim.fn.expand("%:r") .. ".dvi",
    },
  },
  {
    name = "ps2pdf",
    cmd = {'ps2pdf'},
    args = {
      vim.fn.expand('%:p:h') .. '/' .. vim.fn.expand('%:r') .. '.ps'
    }
  }
}
return {
    name = "latex(shell escape) + dvips + ps2pdf",
    builder = function()
      return {
        name = "latex(shell-escape) + dvips + ps2pdf",
        strategy = {
          "orchestrator",
          tasks = tasks,
        },
        components = { { "on_output_quickfix", open = true }, "default" },
      }
    end,
  }
```

**Comment by stevearc** [comment]
It's not that the behavior is undefined, it's that it's unintuitive. The orchestrator strategy requires the `tasks` parameter to be _template definitions_ that point to existing task templates, rather than the raw parameters that will get passed to a task.

I don't think this is very user-friendly, though. It takes some time to even understand the distinction, and the two formats look _very_ similar, so I've updated the orchestrator strategy to accept both template definitions and task parameters. Your example should work now
