### ISSUE TITLE
bug: Targets from included Makefile only visible on first execution

### ISSUE THREAD

**Issue by sieuwerts** [stevearc/overseer.nvim#280]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Describe the bug

When including an external Makefile, the targets are only found by overseer once.
When opening neovim and running `:OverseerRun` I can see that all of my expected targets are there, also if I run `:OverseerInfo` the number of tasks are correct.

However, if I close this window and run either of the commands above again, the targets in the included Makefile is not found.

Restarting Neovim will fix it temporarily, but then again only once. See the Steps to Reproduce for more information.
![image](https://github.com/stevearc/overseer.nvim/assets/42545850/c30405fb-817c-4f99-be3b-03d02ffac3e8)
![image](https://github.com/stevearc/overseer.nvim/assets/42545850/43c6a305-6086-43f8-9a02-04febbbed848)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. Create two Makefiles, one in the project root (will be referred to as the Main Makefile), one in a sub directory (git submodule in my case, will be referred to as Shared Makefile)
2. In the Shared Makefile, add any target, e.g `shared/test`, it doesn't matter what it does.
3. In the Main Makefile, start by adding the line `include ./<subdirectory-where-you-stored-shared-makefile>/Makefile`
4. Add another target in the Main Makefile e.g. `main/test`
5. Now open neovim and run `:OverseerInfo` or `:OverseerRun` and you will see two different make targets available.
6. Close the window with `Esc` (or `q` if info screen).
7. Run `:OverseerInfo` or `:OverseerRun` again and only the target from the Main Makefile is visible in the `Task template` list (or only 1/1 task available on the overseer info screen).
8. On restart of neovim, overseer will find the targets again, but only once.

### Expected Behavior

That the targets from the shared Makefile is available more than once per session.

### Minimal example file

Examples

Main Makefile:
```
include ./subdir/Makefile

main/test:
echo "this is main"
```

Shared Makefile:
```
shared/test:
echo "this is shared"
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    dependencies = {
	"nvim-telescope/telescope.nvim",
	"stevearc/dressing.nvim",
    },
    config = function()
      require("overseer").setup({})
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by NicolasGB** [comment]
Hey! having the exact same problem, when i run a target from a Makefile they all disappear and have to close and open the project again.

Bumping for visibility :D

**Comment by stevearc** [comment]
I tried the repro that you suggested, but it seems to be working fine for me. Could you create a tiny repo with the Makefiles required to see this issue? Also double check that it happens with the minimal repro.lua file you provided (the current one is missing the `plenary` dependency, so OverseerRun errors out).

The only thing I can think of that this could be related to is caching. You could try disabling caching with
```lua
require("overseer").setup({
  template_cache_threshold = 0,
})
```

**Comment by sieuwerts** [comment]
Thank you @stevearc for getting back to me on this, I really want to start using this plugin, it looks amazing. [Here](https://github.com/sieuwerts/overseer-issue-280) is a small repository containing information about how to reproduce the issue and test it. Hopefully it's enough, let me know if there is anything else that you need.

Thanks ⭐

**Comment by stevearc** [comment]
Thanks for the repro repo! It was very helpful; I was able to find the issue right away. Should be fixed now!

**Comment by sieuwerts** [comment]
Thank you! Can confirm that it's been resolved. 🎉
