### ISSUE TITLE
bug: ephemeral docker containers do not stop

### ISSUE THREAD

**Issue by tekulvw** [stevearc/overseer.nvim#290]
### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 13.6

### Describe the bug

I've created a task in `.vscode/tasks.json` that launches a docker container using the command:

```sh
docker run --rm ... postgres:16.2
```

Overseer correctly starts the container but any attempt to `stop` or `dispose` the task (or exitting nvim) does not stop the container. I'm not sure if I've failed to configure something correctly or if this is (un)expected behavior from overseer.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. Create vscode tasks.json from example
2. Run `postgres` task
3. Stop or dispose task or exit nvim (docker ps shows container still running)

### Expected Behavior

Container stops running.

### Minimal example file

```json
{
  "version": "0.2.0",
  "tasks": [
    {
      "type": "shell",
      "label": "postgres",
      "command": "docker run --rm -e POSTGRES_PASSWORD=password postgres:16.2"
    }
  ]
}
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I believe that detaches the docker process. You might need to use `-i` or `-it`

**Comment by tekulvw** [comment]
I still don't get the expected behavior with `-it` using either `dispose` or `stop`.

**Comment by stevearc** [comment]
I found a workaround. If I run the docker command using raw `jobstart()`, then a call to `jobstop()` correctly terminates the container. However, if I set `pty = true` (which we do by default) then the container will _not_ terminate on `jobstop()`. I tested this with some other containers, and they do not have the same behavior (they always clean up properly).

My best guess is that the postgress process behaves differently when it detects a pty and does not respond to the kill signals appropriately. I'm sure there's a good reason for this (if this is indeed what is happening), so it makes the most sense to work around it. You could either configure this for all of your tasks like so:

```lua
require("overseer").setup({
  strategy = { "jobstart", use_terminal = false }
})
```

or you could register a hook to only do it for docker tasks:

```lua
overseer.add_template_hook(nil, function(task_defn, util)
  local cmd = task_defn.cmd
  if (type(cmd) == "string" and cmd:match("^docker ")) or cmd[1] == "docker" then
    task_defn.strategy = { "jobstart", use_terminal = false }
  end
end)
```
