### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by BenjaminLawson** [stevearc/overseer.nvim#292]
### Neovim version (nvim -v)

v0.10.0-dev-2632+ge3bd04f2a

### Operating system/version

Debian

### Describe the bug

The Overseer float task log window does not have an opaque background. The log is mixed with the text in the underlying buffer.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. Open a buffer with text
2. :OverseerToggle
3. select task log and pick "float" option (5)
4. Note that log float does not have an opaque background, and the buffer text is seen through it.

### Expected Behavior

The task log float should have an opaque background.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
This is not a bug, but rather the winblend option which is set in the overseer config and can be customized. However, in this particular case it does remind me that there is an outstanding bug with winblend when the background color is transparent https://github.com/neovim/neovim/issues/18576, which is a good reason to set the default winblend to 0.

**Comment by BenjaminLawson** [comment]
Yep, that fixed it for me! Thank you!
