### ISSUE TITLE
regression: passing `{}` to a task casuses error (API)

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#309]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

Arch Linux

### Describe the bug

* Passing empty list to a task now causes an error. This is a regression.

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

Run the next snippet

```lua 
local overseer = require("overseer")
local tasks = {}

task = overseer.new_task({
  name = "testing regression", strategy = { "orchestrator",
    tasks = {
      tasks,
    }}})
task:start()
```

You will get the next error
![screenshot_2024-06-06_12-52-41_034358831](https://github.com/stevearc/overseer.nvim/assets/3357792/6c679bd9-8eb6-447b-a69d-978333469eb7)

### Expected Behavior

* The old (desired) behavior is to just  ignore the empty task without errors.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

local overseer = require("overseer")
local tasks = {}

task = overseer.new_task({
  name = "testing regression", strategy = { "orchestrator",
    tasks = {
      tasks,
    }}})
task:start()
```

### Additional context
* Tested on the latest overseer commit: a6dc0600f675f10b8840c61d3f9d72fdf8cf970c
* This regression has been introduced in recent versions.

**Comment by Zeioth** [comment]
about the DAP warning it doesn't display if I set
```lua
opts = {
  dap = false
}
```
but I imagine once DAP releases its next version this won't be necessary.

**Comment by stevearc** [comment]
Should be fixed now

**Comment by Zeioth** [comment]
Tested and fixed indeed!
