### ISSUE TITLE
bug: When using fzf-lua ui.select adding a component fails

### ISSUE THREAD

**Issue by xyven1** [stevearc/overseer.nvim#311]
### Neovim version (nvim -v)

0.10.0 commit f69937fdbd162630c35e119e67bbbf052558c0e0

### Operating system/version

NixOS 24.11.20240531.57610d2

### Describe the bug

When in the task editor, after hitting `o` the `vim.ui.select` window (as provided by fzf-lua) pops up, but the focus is maintained on the overseer window, and for all intents and purposes the `vim.ui.select` window is dead (even after navigating to the window the key binds dont work). I'm not sure if this an issue with the implementation of `vim.ui.select` by fzf-lua, but my best guess is that it has to do with the way that overseer manages the cursor in the edit popup. For clarity the selector provided by fzf-lua opens a floating window, and then the cursor immediately jumps back to the overseer editor window.

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. Create new task with overseer
2. hit `o`

### Expected Behavior

The ui select window maintains focus until an item is selected.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  }, 
  {
    'ibhagwan/fzf-lua',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function(_, opts)
      local fzf = require('fzf-lua')
      fzf.setup(opts or {})
      fzf.register_ui_select(function(_, items)
        local min_h, max_h = 0.15, 0.70
        local h = (#items + 4) / vim.o.lines
        if h < min_h then
          h = min_h
        elseif h > max_h then
          h = max_h
        end
        return { winopts = { height = h, width = 0.60, row = 0.40 } }
      end)
    end
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by xyven1** [comment]
Weirdly this behavior is also the same with `telecsope-ui-select.nvim` so maybe the issue is somewhere else in my config? There aren't really any other moving components with `vim.ui.select` though...

**Comment by stevearc** [comment]
I tested this and managed to reproduce it _sometimes_. There seems to be a race condition when opening the `vim.ui.select` UI. I added a slight delay that seems to have fixed the issue for me, can you test it?

**Comment by xyven1** [comment]
@stevearc Ah, interesting. For me it's 100%, whether it's telescope or fzf-lua. I can test it in about an hour, thanks for the quick fix.

**Comment by xyven1** [comment]
@stevearc Seems to have addressed the issue, no problems now. Also there is no noticeable delay when editing the task, so that is nice!
