### ISSUE TITLE
bug:  [ NOT FIXED ]Shortcut for ScrollOutout does not work anymore

### ISSUE THREAD

**Issue by MrMic** [stevearc/overseer.nvim#312]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

linux / Ubuntu 22.04

### Describe the bug

When I start a task I  cannot scroll the output 
with: Ctrl-j or Ctrl-k

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

Press Ctrl-j or Ctrl-k to scroll the ScrollOutput panel

### Expected Behavior

scroll the output as It works before

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Should be fixed now. Thanks for the report!

**Comment by MrMic** [comment]
@stevearc  I have updated but I still  have the bug... 😞

**Comment by stevearc** [comment]
@MrMic how are you opening the task output? I'm testing by doing
1. `:OverseerOpen`
2. Then from the task list, `p` to open the preview
3. Then `<C-k>` to scroll up

Ah, you're probably using it for the built-in output window aligned to the bottom of the editor, next to the task list?

**Comment by MrMic** [comment]
Yes! The content next to the task list does not scroll anymore with the shortcuts

**Comment by stevearc** [comment]
Okay, another fix went in that should cover that case as well

**Comment by MrMic** [comment]
Yes! It is OK now.
Thanks.
Rgds,
