### ISSUE TITLE
regression: in commit `refactor: change default params of open_output component`

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#313]
### Neovim version (nvim -v)

0.10

### Operating system/version

arch linux

### Describe the bug

There seem something broke in the commit bd9cc6d2cc2317b6b70b3bfb956c88d4e00c7837, because the previous commit 29dd31db39b44ddd57cfbc70610181a23acfae47 seem to be working fine.

![screenshot_2024-06-09_18-51-03_597997129](https://github.com/stevearc/overseer.nvim/assets/3357792/37ecf42b-459d-4932-9973-90c4ffe88d26)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

You can try it with the PR you sent to compiler.nvim.

### Expected Behavior

Run without errors.

**Comment by stevearc** [comment]
My apologies, I forgot that when defining the types for the parameters that I actually do hard validation checks. I changed the type of the `on_start` param. I'll submit a PR to compiler.nvim to fix this
