### ISSUE TITLE
bug: the component `on_complete_notify` behaves inconsistenly

### ISSUE THREAD

**Issue by Zeioth** [stevearc/overseer.nvim#316]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

arch linux

## What works
assuming the next config 
```lua
component_aliases = {
  default = {
    "on_exit_set_status",
    "on_complete_notify",
    "open_output"
  },
},
```
The tasklist will is updated every time a notification is sent to the user (which is, every time a task start).

## What doesn't 
If we remove `"on_complete_notify"`, the tasklist will update every n ticks (time based, unless I'm wrong).

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

1. On unix and having compiler.nvim installed run: `:luafile ~/.local/share/nvim/lazy/compiler.nvim/tests/tests.lua`

the tasklist will take a long time to update (10-20 seconds) unless the component `on_complete_notify` is present. I assume the time ticks are actually shorter (1s?), but because the tests use `vim.wait()` that is interfering. Which may also happen to users.

### Expected Behavior

The tasklist should be updated every time a task starts (no matter if the component `on_complete_notify` is present). The only difference must be we don't send notifications, other behaviors shouldn't change.

**Comment by stevearc** [comment]
The UI is not updating because you're blocking the main thread with `vim.wait`. If you want the UI to update, you'll have to use callbacks with `vim.defer_fn`, or an async library like nvim-nio or plenary, or you could do the same thing yourself with raw coroutines, like so:

```lua
local language = require("compiler.languages.cpp")
local example = vim.fn.stdpath("data")
  .. "/lazy/compiler.nvim/tests/code samples/languages/cpp/"

coroutine.resume(coroutine.create(function()
  local co = coroutine.running()
  local function sleep()
    vim.defer_fn(function() coroutine.resume(co) end, 1000)
    coroutine.yield()
  end

  -- Build and run
  vim.api.nvim_set_current_dir(example .. "build-and-run/")
  language.action("option1")
  sleep()

  -- Build
  vim.api.nvim_set_current_dir(example .. "build/")
  language.action("option2")
  sleep()

  -- Run
  language.action("option3")
  sleep()

  -- Build solution (without .solution file)
  vim.api.nvim_set_current_dir(example .. "solution-nofile/")
  language.action("option4")
  sleep()

  -- Build solution
  vim.api.nvim_set_current_dir(example .. "solution/")
  language.action("option4")
  sleep()
end))
```

**Comment by Zeioth** [comment]
I can't even start to tell you how grateful I am for that snippet @stevearc. Thank you, that fixes it indeed.
