### ISSUE TITLE
Custom errorformat for cargo template

### ISSUE THREAD

**Issue by Shatur** [stevearc/overseer.nvim#33]
Sending output from Cargo to quickfix results in wrongly matched errors.
[Here](https://github.com/Shatur/neovim-rust/blob/50dec57cde65e16c05096316ee2644fe45e6427d/lua/rust/utils.lua#L10) is how is how errorformat should look for it.
Could we have a custom `errorformat` for templates or actions from them? If yes, could we override it for cargo template?

**Comment by stevearc** [comment]
How are you sending the output to the quickfix? The [on_output_quickfix component](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md#on_output_quickfix) has a parameter to customize the errorformat.

I also just added some better utilities for customizing the components of a template or template provider.
https://github.com/stevearc/overseer.nvim/blob/d410e8fc129d3fbf6ee515669f5f3dad1db7112c/lua/overseer/init.lua#L308-L320

All together, I think this should do what you want:
```lua
  overseer.hook_template("cargo", function(task_defn, util)
    util.add_component(task_defn, {
      "on_output_quickfix",
      errorformat = [[%Eerror: %\%%(aborting %\|could not compile%\)%\@!%m,]]
        .. [[%Eerror[E%n]: %m,]]
        .. [[%Inote: %m,]]
        .. [[%Wwarning: %\%%(%.%# warning%\)%\@!%m,]]
        .. [[%C %#--> %f:%l:%c,]]
        .. [[%E  left:%m,%C right:%m %f:%l:%c,%Z,]]
        .. [[%.%#panicked at \'%m\'\, %f:%l:%c]]
    })
  end)
```

**Comment by Shatur** [comment]
> How are you sending the output to the quickfix?

I just used an action on task from Telescope.

> All together, I think this should do what you want:

Thank you!
Should we hook this by default? Otherwise Cargo messages will have wrong filenames capture.

**Comment by stevearc** [comment]
Hmmm...this will take some more thought. We don't want to automatically add the `on_output_quickfix` component to all the cargo tasks, but we would like to provide a default value for `errorformat` if the component _is_ added. We would also like to use that in the "set quickfix" action. I have the seeds of an idea for this; will play around with it and see if it works out.

**Comment by Shatur** [comment]
Thank you a lot, a very convenient feature!
