### ISSUE TITLE
Add a command to re-run last task

### ISSUE THREAD

**Issue by Shatur** [stevearc/overseer.nvim#34]
It would be nice to be able to restart the last task using a command.
Useful if you run the same task frequently.

**Comment by stevearc** [comment]
This is pretty easy to add yourself!
```lua
vim.api.nvim_create_user_command("OverseerRestartLast", function()
  local overseer = require("overseer")
  local tasks = overseer.list_tasks({ recent_first = true })
  if vim.tbl_isempty(tasks) then
    vim.notify("No tasks found", vim.log.levels.WARN)
  else
    overseer.run_action(tasks[1], "restart")
  end
end, {})
```

I don't think I want to add this as a built-in command, but this would be a good candidate for a "recipes" section of the docs. I'm in the process of overhauling the documentation at the moment, so I'll make sure that gets added.

**Comment by Shatur** [comment]
Got it, thank you!
