### ISSUE TITLE
Open Overseer when a task is started

### ISSUE THREAD

**Issue by Shatur** [stevearc/overseer.nvim#36]
It's more a question about API. I would like to create a shortcut to run a template. And I would like to open Overseer after selecting a task to see the task progress. I currently use the following:
```lua
vim.keymap.set('n', '<A-t>', function()
  overseer.open({ enter = false })
  overseer.run_template()
end, { noremap = true })
```
But is it possible to open Overseer only after selection?

**Comment by stevearc** [comment]
You should be able to do
```lua
overseer.run_template(nil, function(task)
  if task then
    overseer.open({ enter = false })
  end
end)
```

**Comment by Shatur** [comment]
Thank you a lot!
Sorry for a lot of questions, just trying to catch up the API :)

**Comment by stevearc** [comment]
No worries! The docs are a bit lacking right now. If you want to preview the updated API docs, you can find them here: https://github.com/stevearc/overseer.nvim/blob/stevearc-doc/doc/reference.md#lua-api
