### ISSUE TITLE
bug: custom errorformat with overseer breaks neovim ui

### ISSUE THREAD

**Issue by monkoose** [stevearc/overseer.nvim#377]
### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

Custom `errorformat` and using overseer task with
```lua
components = {  { "on_output_quickfix", open = true }, "default"  },
```
 totally breaks neovim ui (non floating windows and statusline become hidden)

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. Run `nvim -u minimal.lua`
2. Execute `OverseerRun ls`
3. For better understanding what is going on run `:copen`

It seems like some multiple windows have opened, and multiple `:q` doesn't quit neovim, only like third I guess.

### Expected Behavior

Plugin shouldn't break neovim ui in any way no matter which options user uses.

### Minimal init.lua

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.errorformat:append([[,%f\|%\s%#%l col%\s%#%c%\s%#\| %m]])
-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/overseer.nvim",
    config = function()
      local overseer = require("overseer")
      overseer.setup({})
      overseer.register_template({
        name = "ls",
        builder = function()
          return {
            cmd = { "ls" },
            components = {
              { "on_output_quickfix", open = true },
              "default",
            },
          }
        end,
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
vim.cmd.colorscheme("tokyonight")
```

**Comment by stevearc** [comment]
Could you use a minimal init.lua file to reproduce the issue, as is requested in the bug report template?

**Comment by monkoose** [comment]
I have updated issue.

**Comment by stevearc** [comment]
Thanks for making the repro! I was able to find the issue pretty quickly. There was a utility method that needs to create a fullscreen float, do some operation in that context, then close the float. The errorformat is invalid and was causing a crash during that middle operation, so we weren't cleaning up the float afterwards. I've properly guarded against this behavior now with `xpcall`, but you'll still have to figure out how to fix your errorformat

**Comment by monkoose** [comment]
Thanks. Before this happen, I want aware that it is broken, I have translated it from my old vim config, , and now I'm not even remember why I had it in the config, so I have commented out it anyway.
