### ISSUE TITLE
Error executing vim.schedule lua callback: ...seer.nvim/lua/overseer/component/on_output_summarize.lua:8

### ISSUE THREAD

**Issue by redirect11** [stevearc/overseer.nvim#39]
Hi, like in the title, I get this error message after a task is finished: 

```
Error executing vim.schedule lua callback: ...seer.nvim/lua/overseer/component/on_output_summarize.lua:8: Invalid buffer id: 245
stack traceback:
        [C]: in function 'nvim_buf_line_count'
        ...seer.nvim/lua/overseer/component/on_output_summarize.lua:8: in function 'get_last_lines'
        ...seer.nvim/lua/overseer/component/on_output_summarize.lua:42: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It happens when a task is finished, and I have a float (but also vertical and horizontal) terminal is open. The same happens if I do Ctrl+C to stop the task. I'm using NvChad.

Not related: when a task is completed I cannot see vim.notify popup. I have the plugin nvim-notify,

**Comment by stevearc** [comment]
I wrapped the call with a buffer valid check; should fix the issue.

Have you configured nvim-notify to be your vim.notify handler?
```lua
vim.notify = require("notify")
```
