### ISSUE TITLE
Attach to terminal

### ISSUE THREAD

**Issue by ayoubelmhamdi** [stevearc/overseer.nvim#44]
When I close Buf of `terminal`, I should have to restart the `task` to view the output. Is there, is there a way to reattach to output, without taping?
```vim
: OverseerQuickAction
restart
:OverseerQuickAction
8 vsplit
```

**Comment by ayoubelmhamdi** [comment]
I think you believe, I'm asking how to `start terminal in insert mode`, already configured `terminal` to start in insert e mode`,

my question is: `how to restore windows that include the terminal not mode of terminal` do you understand my question, Mr @stevearc ?

**Comment by stevearc** [comment]
Sorry, I may have gone too far into the weeds in my first comment. Let me simplify:

* There is no "restore" or "undo" operation for window layout. If you closed the window with the terminal buffer, you will need to open a new window with the terminal buffer.
* To display the task buffer in a window you can use the `open`, `open vsplit`, `open hsplit`, or `open float` actions. This works equally well on running and completed tasks.
* If you want to bypass actions entirely, the task instance has a `task:get_bufnr()` method that will return the buffer number (or nil, if the buffer has been deleted). You can do whatever you want with that handle.
* If you have deleted the buffer for a task, the buffer is irrecoverably gone and you will need to restart the task or run a new one if you want to see the output.

Does that answer your question?

**Comment by ayoubelmhamdi** [comment]
Yes, that is my answer that I want? Thinks,

so, `the buffer of terminal `not hidden, it's gone, 

tell me, please, when I use  `oversser` on `watch` mode, the **terminal** is gone, is there any `lua function` or `:vim comand` that can execute the `open vsplit`, without using `ui`  like:
```vim
:OverseerOpenvsplite last-task
```

**Comment by stevearc** [comment]
`:OverseerQuickAction open vsplit` will run the `open vsplit` action on the most recent task.

You could get the same effect by using [overseer.list_tasks()](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#list_tasksopts) to get the task and then calling [overseer.run_action()](https://github.com/stevearc/overseer.nvim/blob/master/doc/reference.md#run_actiontask-name)

**Comment by ayoubelmhamdi** [comment]
Thanks so much @stevearc
