### ISSUE TITLE
Append outputs when saving file

### ISSUE THREAD

**Issue by Antonio-Costa00** [stevearc/overseer.nvim#47]
Hello. Thank you for the great plugin. Is it possible to append new outputs on the screen when saving the file?

**Comment by stevearc** [comment]
What do you mean by "append new outputs"? Could you describe you situation and what you want to accomplish it a bit more detail?

**Comment by stevearc** [comment]
I'm not sure what you mean by this. By default, overseer tasks stick around for a while (see [the FAQ](https://github.com/stevearc/overseer.nvim/blob/master/doc/explanation.md#faq) for ways to alter how long they stay). There certainly is no default logic that destroys previous tasks when a new one is run.

Here's a quick example showing multiple tasks run in succession, with the output still available for all of them.
https://user-images.githubusercontent.com/506791/196598614-9173dc7f-30a6-48aa-aec1-3c47dbe2d721.mp4

**Comment by Antonio-Costa00** [comment]
When you execute the same task again the old output disappears. If possible, I want to know if it's possible to have a history of the tasks, like this for example
![image](https://user-images.githubusercontent.com/87380701/197090143-6232b257-2733-4f94-9a15-9c27d68aeced.png)

**Comment by stevearc** [comment]
Ah, you want the output of all runs to be appended to the same buffer. I can think of a couple ways to do that, but it's a chunkier project so it'll take me a bit of time to get to it (I'm trying to push out a large refactor of aerial.nvim at the moment)

**Comment by Antonio-Costa00** [comment]
Hehe, that's okay. Thank you for your attention.

**Comment by stevearc** [comment]
This is now possible! The default run strategy with overseer uses the built-in terminal (via `termopen`). I've added a new one that uses `jobstart`, and handles the input/output communication with `nvim_open_term`. This gives us a bit more flexibility in how we use the buffer, so we can decide to preserve the output from previous runs. To get this behavior, set the default strategy:

```lua
require("overseer").setup({
  strategy = { "jobstart", preserve_output = true },
})
```

**Comment by Antonio-Costa00** [comment]
Thank you so much! I will have a try!
