### ISSUE TITLE
This file %

### ISSUE THREAD

**Issue by ayoubelmhamdi** [stevearc/overseer.nvim#49]
How can I use `%` or `%:p`... in cmd to expand current file.

Like:
```
%
# or
./script.sh %
# or 
./script "a:%:b"
```
![image](https://user-images.githubusercontent.com/34358145/196055212-c5648c8c-8d41-4053-8e13-e832eb5027ee.png)

**Comment by stevearc** [comment]
I've pushed up a change that should make it so that the shell template expands its cmd by default. LMK if you find other situations where it makes sense for these shortcuts to work

**Comment by ayoubelmhamdi** [comment]
error with:
```
cmd: %
# or
cmd: bash %
```
![image](https://user-images.githubusercontent.com/34358145/196666107-2bc3dc8f-af81-41d3-99ad-6b823ca05024.png)

**Comment by ayoubelmhamdi** [comment]
It's work fine, thanks so much

**Comment by stevearc** [comment]
Glad to hear it!
