### ISSUE TITLE
sugg: watch off

### ISSUE THREAD

**Issue by ayoubelmhamdi** [stevearc/overseer.nvim#51]
The `watch` feature is very useful, but sometimes, we want to stop it from menu

![image](https://user-images.githubusercontent.com/34358145/197357976-c0b47653-6102-4928-99ae-bbc1148f6a1f.png)

could you add `watch off` in the menu
# TO BE

![image](https://user-images.githubusercontent.com/34358145/197358040-5786a55a-fcfa-4b1a-b99a-0f8431c48867.png)

**Comment by stevearc** [comment]
Sure! I've added an `unwatch` command, but also just in case you were curious, you can do this entirely in your own config!

```lua
require("overseer").setup({
  actions = {
    unwatch = {
      desc = "Remove the file watcher",
      condition = function(task)
        return task:has_component("restart_on_save")
      end,
      run = function(task)
        task:remove_component("restart_on_save")
      end,
    },
  },
})
```

Check the [actions guide](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#actions) for more

**Comment by ayoubelmhamdi** [comment]
That's great
