### ISSUE TITLE
Neotest no longer works in latest commit

### ISSUE THREAD

**Issue by olimorris** [stevearc/overseer.nvim#55]
I've noticed that since commit d9e63c3e387d6acac9fb08643ce26c4686eb5c30, when I run `lua require("neotest").run.run()`, it just hangs.

Rolling back to 5f16178372fe24d5afa7f5cb871c5a86548e886b solves this.

**Comment by stevearc** [comment]
Well this is embarrassing. I inverted the logic in a very important if-statement 😅
Apologies for the thrash!

**Comment by olimorris** [comment]
No problem and speedy to resolve
