### ISSUE TITLE
i get no default tasks

### ISSUE THREAD

**Issue by grammenoudis** [stevearc/overseer.nvim#56]
i installed the plugin with packer, set it up in my init.lua as it says, but still there are no default tasks (VSCode tasks)

**Comment by stevearc** [comment]
I've pushed up a change that adds a new `:OverseerInfo` command that displays some diagnostic information. Could you run that and paste the output here?
Also, the command will show you the location of the log file. Could you check that file and see if there are any warnings or errors?

**Comment by grammenoudis** [comment]
> 

`[ERROR] Error loading template 'user.cpp_build': module 'overseer.template.user.cpp_build' not found:
	no field package.preload['overseer.template.user.cpp_build']
	no file './overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build/init.lua'
	no file './overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file './overseer.so'
	no file '/usr/local/lib/lua/5.1/overseer.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer.so'
[ERROR] Error loading template 'user.cpp_build': module 'overseer.template.user.cpp_build' not found:
	no field package.preload['overseer.template.user.cpp_build']
	no file './overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build/init.lua'
	no file './overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file './overseer.so'
	no file '/usr/local/lib/lua/5.1/overseer.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer.so'
[ERROR] Error loading template 'user.cpp_build': module 'overseer.template.user.cpp_build' not found:
	no field package.preload['overseer.template.user.cpp_build']
	no file './overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build/init.lua'
	no file './overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file './overseer.so'
	no file '/usr/local/lib/lua/5.1/overseer.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer.so'
[ERROR] Error loading template 'user.cpp_build': module 'overseer.template.user.cpp_build' not found:
	no field package.preload['overseer.template.user.cpp_build']
	no file './overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/usr/local/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/opt/homebrew/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/overseer/template/user/cpp_build/init.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build.lua'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/overseer/template/user/cpp_build/init.lua'
	no file './overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer/template/user/cpp_build.so'
	no file './overseer.so'
	no file '/usr/local/lib/lua/5.1/overseer.so'
	no file '/opt/homebrew/lib/lua/5.1/overseer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/grammenoudis/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/overseer.so'`

**Comment by stevearc** [comment]
Okay, so that looks like you're trying to use a custom template but the file isn't in the correct location. That's a separate issue and while it means your custom template won't work, it shouldn't impact VS Code task loading.

What is your overseer config? And what is the output of `:OverseerInfo`?

**Comment by grammenoudis** [comment]
> Okay, so that looks like you're trying to use a custom template but the file isn't in the correct location. That's a separate issue and while it means your custom template won't work, it shouldn't impact VS Code task loading.
> 
> What is your overseer config? And what is the output of `:OverseerInfo`?

i already posted the :OverseerInfo output, also, the command that says it failed to load is actually running fine, and the files exist at the places that they should

`└── template
    └── user
        └── cpp_build.lua
`
