### ISSUE TITLE
tasks.json input does not prompt when default is set

### ISSUE THREAD

**Issue by wyrid** [stevearc/overseer.nvim#57]
I have a task in .vscode/tasks.json that uses an input variable. When the input variable does not have a default value set, it works as expected and prompts for a value. However, if I add a default value to the input variable, it does not prompt at all but instead runs the task using the default value.

I would expect that it should prompt you to override the default input before running the task instead of immediately executing with the default value.

```jsonc
{
  "version": "0.0.1",
  "tasks": [
    {
      "label": "Task",
      "type": "shell",
      "command": "echo \"${myVariable}\""
    }
  ],
  "inputs": [
    {
      "id": "myVariable",
      "type": "promptString",
      "description": "A value to echo",
      // Without this, it prompts. With this, it skips the prompt and immediately uses "default_value"
      "default": "default_value",
    }
  ]
}
```

**Comment by wyrid** [comment]
Nevermind, I managed to figure it out. I did not realize that `default_template_prompt` would prevent it from showing unless it was set to `always`.

**Comment by stevearc** [comment]
Honestly, I haven't quite been happy with the configurability of this behavior. One of the issues is that it treats parameters that set `optional = true` and parameters with a default value equivalently. While you did find a workaround, I think it's obvious that this is not good default behavior.

I just pushed a commit that changes how `default_template_prompt = "allow"` works. It should now prompt any time a non-optional parameter needs a value, which I believe is what you're looking for. The old behavior can be restored by setting `default_template_prompt = "avoid"`. More details are in the commit message.

Let me know if you have any additional feedback!
