### ISSUE TITLE
Incorrect paths in quickfix using on_output_quickfix

### ISSUE THREAD

**Issue by stevearc** [stevearc/overseer.nvim#59]
I'm doing a follow-up here because it's related with the above (I can open a new issue if you want). 

So things mostly work great after your pointers but I'm having an issue such that if my current working directory (`/home/pedro/Desktop`)  is not that of the file I'm currently editing (`/home/pedro/Desktop/test-latex`) then when the quickfix opens and I jump to an error I'm taken to a new empty file (see GIF below). If I make the current file directory the working directory then jumping works as expected (since now the quickfix correctly parses the `.tex` file location). So my question is: how can I set the "quickfix working  directory" to that of the current file?

![overseer_pwd](https://user-images.githubusercontent.com/2583971/198914067-105cd82d-faa8-4a83-ba18-177932f6d1aa.gif)

_Originally posted by @petobens in https://github.com/stevearc/overseer.nvim/issues/45#issuecomment-1296433656_

**Comment by stevearc** [comment]
From the gif, it looks like the quickfix items have an absolute path to the file. From my tests, `getqflines` (which is what I'm using to parse the program output) won't convert relative paths to absolute ones, so that makes me think the output of the task is spitting out the wrong paths. What's the raw output of the command you're running? What format are the file paths in that output?

**Comment by petobens** [comment]
They seem to be relative paths:
```
./foo.tex:5: Undefined control sequence.
```
Using lcd seems to make everything work as expected but dunno if this is the correct way to proceed:
```lua
local compile_latex = function()
    local current_pwd = vim.fn.getcwd()

    vim.cmd('silent noautocmd update')
    vim.cmd('lcd %:p:h')
    overseer.run_template({ name = 'run_arara' }, function(task)
        vim.cmd('cclose')
        task:subscribe('on_complete', function()
            local log_file = vim.fn.fnamemodify(task.metadata.filename, ':p:r') .. '.log'
            _parse_logfile(log_file)
            vim.cmd('lcd ' .. current_pwd)
        end)
    end)
end
```
I can live with this `lcd` hacking (but maybe you have a better incantation).

**Comment by stevearc** [comment]
Okay great, the fact that it's relative filepaths confirms my suspicion. I'm not sure if I'll be able to find a better fix, but I'll give it a shot

**Comment by stevearc** [comment]
Okay, I have a slightly less hacky way of handling relative filepaths, but so far I've only fixed it for the `on_output_quickfix` component. In your example you are parsing a log file and handling the quickfix logic yourself. If it's possible for you to send the data to stdout instead and use the `on_output_quickfix` component, that would probably be the easier solution (note that it relies on the task cwd, so you would need to `overseer.run_template({ name = 'run_arara', cwd = vim.fn.expand('%:p:h')}, ...`).

If you need to keep handling the quickfix yourself, you can use the `util.run_in_cwd` function that I'm using in the on_output_quickfix component
https://github.com/stevearc/overseer.nvim/blob/42c89a24c5f3dc13067fa4aee3467cc51125b531/lua/overseer/component/on_output_quickfix.lua#L102-L108

Note that this uses an api in `overseer.util`, which is not _technically_ public and therefore does not have stability guarantees. It will most likely not change for a good long while, but if it does you may just get an error instead of a nice migration message. Alternatively, you're welcome to copy the code itself into your dotfiles and use it directly.

pro-tip if you decide to use `on_output_quickfix`: your task builder can define a default errorformat for components/actions. You can see an example of how to do that in the cargo template:
https://github.com/stevearc/overseer.nvim/blob/42c89a24c5f3dc13067fa4aee3467cc51125b531/lua/overseer/template/cargo.lua#L18-L26

**Comment by petobens** [comment]
Awesome thanks!!
