### ISSUE TITLE
Add `direction = "bottom"` option

### ISSUE THREAD

**Issue by yutkat** [stevearc/overseer.nvim#6]
I want the task results to open bottom style like VS Code.
So I'd like to add the option `direction = "bottom"`.

**Comment by stevearc** [comment]
When you say "task results", are you talking about the output terminal? There's currently actions that "open", "open vsplit", and "open float", am I correct in thinking that what you're asking for is something that's like "open bottom" that opens the terminal in a `botright split`?

Another possibility would be (more like VS Code) to have some way to open a dedicated window at the bottom of the editor, and any time a new task is started update that window to display the terminal for that task.

**Comment by yutkat** [comment]
In the meantime, I am talking about I want to open the task list(?) at the bottom.

I want to use it like this: `OverseerOpen bottom`

BTW, It's also inconvenient that there is no `open split` in the task result. I prefer to use split rather than vsplit.

**Comment by stevearc** [comment]
Oh, I didn't even think about opening the task list on the bottom. It's a vertically scrolling list that doesn't take up a lot of horizontal space, so a lot of the right side would be empty. Is this what you're picturing?

```
+-----------------------------------+
|                                   |
|          main editor win          |
|                                   |
|                                   |
+------------------------------------
| Task 1                            |
| Task 2                            |
+-----------------------------------+
```

Added a `open hsplit` action.

**Comment by yutkat** [comment]
Yes, That's what I wanted to do.
I see. It certainly increases the amount of invalid space.
I'll try to use overseer some more and I'll get used to it.

> Added a open hsplit action.

Thank you very much!

**Comment by yutkat** [comment]
Also, I'd like to add Hsplit here.
https://github.com/stevearc/overseer.nvim/blob/fa303c24e765df563d81513917479e2ce09a8669/lua/overseer/task_list/bindings.lua#L32-L38

**Comment by stevearc** [comment]
Done!
