### ISSUE TITLE
Cannot see output when task finish

### ISSUE THREAD

**Issue by redirect11** [stevearc/overseer.nvim#61]
Hi, there is a way to avoid overseer to close the open floating terminal when a task finish? I have some VS Code shell task that I run with overseer that, when the task terminates, closes the floating terminal and I cannot re-open it so I cannot see the output of the task.

As alternative, I saw that is possible to show the output in quickfix buffer. There is a way to do it with a VS Code task?

Offtopic: is there an api to list all tasks defined in tasks.json? I'd like to associate tasks in tasks.json automatically to a key mapping using which-key. Do you now if it possible doing something like this? 

Offtopic2: since my compilation scripts accepts arguments from command line to build different application variants, I would like to spawn a selection menu, after selecting the task to run, to select the build variant and pass the relative command argument to the script lunched by the task. The task is defined in tasks.json. Is it possible to do something like that?

**Comment by stevearc** [comment]
> is a way to avoid overseer to close the open floating terminal when a task finish?

I'm surprised by this question because by default when a task finishes it should notify and start a timer for cleanup, but nothing else. Can you provide a minimal config + command that reproduces this?

> I saw that is possible to show the output in quickfix buffer. There is a way to do it with a VS Code task?

Yes, I thought I documented this, but I guess I didn't. You can specify custom components for VS Code tasks by using the `default_vscode` component alias

```lua
require("overseer").setup({
  component_aliases = {
    default_vscode = {
      "default",
      "on_output_quickfix",
    },
  },
})
```
I'll add some documentation about this

> is there an api to list all tasks defined in tasks.json?

The _official_ API doesn't have this, but there is an unofficial API that is nonetheless mostly stable. I may decide to promote this to a supported interface

```lua
require("overseer.template").list({
  dir = vim.fn.getcwd(),
}, function(templates)
  for _, tmpl in ipairs(templates) do
    if tmpl.module == "vscode" then
      print(string.format("tmpl %s", tmpl.name))
    end
  end
end)
```

I need to go get on a plane, but I'll come back to this after this weekend

**Comment by redirect11** [comment]
> I'm surprised by this question because by default when a task finishes it should notify and start a timer for cleanup, but nothing else. Can you provide a minimal config + command that reproduces this?

On the project I'm workign on, we use `make` to run commands on a docker running instance. Something like: 

```
make docker_run_cmd ......
```
I'll try to reproduce it with a simple configuration. I have no problem with scripts that returns exit codes

**Comment by redirect11** [comment]
Hi again. Sorry but still didn't had the time to get a working example for my issue. In the meantime I would like to come back to something related to the "Offtopic2" question: I would like to show a file chooser dialog (or a list of file that follow a specific naming pattern) when I select a task to run against a specific file. I was looking into VS Code variable substitution but I still don't know how to achieve this.

**Comment by stevearc** [comment]
I don't think tasks.json supports that exactly. From the [VS Code docs](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables), `pickString` lets you specify a set of options, but there's no way to dynamically generate options based on a file pattern.

If you want to run the task on the currently-open file, you can use the `${file}` variable as described in the [Predefined variables section](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables).

**Comment by stevearc** [comment]
The first example using `pickString` is supported, the second with `extension.commandvariable.pickStringRemember` is not.
