### ISSUE TITLE
[Feature] Expand vim variables in `cmd` string

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/overseer.nvim#63]
I'm defining a task like this:

![image](https://user-images.githubusercontent.com/13739892/202412805-8c1d69bc-f520-48b6-bbfd-2b97c02c871e.png)

It would be great to add a way to pass the current filename without extension to the cmd string, for example.

**Comment by stevearc** [comment]
It sounds to me like you're trying to create a reusable task that runs on the current file in the current directory. If that's the case, have you tried using [task templates](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-tasks)? This is how I would recommend making a reusable task.

```lua
overseer.register_template({
  name = "My task",
  builder = function()
    return {
      cmd = vim.fn.expand("ghdl -m -fsynopsys -fexplicit -f %:t:r"),
      cwd = vim.fn.expand("%:h"),
    }
  end,
})
```

**Comment by pidgeon777** [comment]
Unfortunately, this piece of code is not working:

```lua
cmd = vim.fn.expand("ghdl -m -fsynopsys -fexplicit -f %:t:r")
```

If you try this in Neovim:

```lua
lua print(vim.fn.expand("ghdl -m -fsynopsys -fexplicit -f %:t:r"))
```

Then the following string is printed:

```lua
ghdl -m -fsynopsys -fexplicit -f %:t:r
```

The variable is not expanded, and the command as a consequence is not recognized when run.

**Comment by stevearc** [comment]
Apologies, try `vim.fn.expandcmd("ghdl -m -fsynopsys -fexplicit -f %:t:r")`

See `:help expand()` and `:help expandcmd()` for more info

**Comment by pidgeon777** [comment]
It works 👍.

I have a question, how can I select and delete a specific task on the panel:?

![image](https://user-images.githubusercontent.com/13739892/202861002-3800a7e0-d88f-40d0-876f-89538d99086d.png)

For example, I would like to delete the first two tasks.

**Comment by pidgeon777** [comment]
Never mind, there is the command `dispose` for that.
