### ISSUE TITLE
[Bug] Error running config at `PackerSync` and at first `overseer.nvim` command execution

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/overseer.nvim#64]
nvim version:

```
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilato da runneradmin@fv-az177-603
```

overseer.nvim setup:

```lua
{
  "stevearc/overseer.nvim",
  config = function()
    require("overseer").setup()
  end,
},
```

When running `PackerSync` command with the config above, thus during the generation of `packer_compiled.lua` file, Neovim returns:

```log
packer.nvim: Error running config for overseer.nvim: ...acker\start\overseer.nvim/lua\overseer\template\init.lua:170: name: expected string, got nil
```

During a subsequent Neovim startup no error is reported, though. But If I try to run any of the `overseer.nvim` commands, the same error is reported:

```lua
Error executing Lua callback: ...acker\start\overseer.nvim/lua\overseer\template\init.lua:170: name: expected string, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua:699: in function 'validate'
	...acker\start\overseer.nvim/lua\overseer\template\init.lua:170: in function 'validate_template_provider'
	...acker\start\overseer.nvim/lua\overseer\template\init.lua:290: in function <...acker\start\overseer.nvim/lua\overseer\template\init.lua:288>
	...te\pack\packer\start\overseer.nvim/lua\overseer\init.lua:104: in function 'cb'
	...te\pack\packer\start\overseer.nvim/lua\overseer\init.lua:79: in function 'do_setup'
	...te\pack\packer\start\overseer.nvim/lua\overseer\init.lua:88: in function <...te\pack\packer\start\overseer.nvim/lua\overseer\init.lua:87>
```

But when I try to run any of the `overseer.nvim` commands again, no error is reported.

Tested with latest `overseer.nvim` commit:

https://github.com/stevearc/overseer.nvim/commit/83d5bc09f1d416cadad205d111f948762007a55c

Tested on Windows 10 Pro.

**Comment by pidgeon777** [comment]
This is probably due to:

1. A wrong user configuration.
2. `PackerSync` not correctly regenerating `packer_compiled.lua`.

I'll investigate a bit and leave this issue open.

**Comment by stevearc** [comment]
Do you have any other config for overseer? I can see how this error would occur, but the only way I think it's possible is if you call `overseer.register_template` directly at some point (passing in a template definition with no name).

I've also pushed up 3427960953ae27448a1022aed2f9fef3e1de43ac which should catch and log more information about errors during the startup process.

**Comment by pidgeon777** [comment]
My fault, `packer_compiled.lua` wasn't generated sometimes, and the default `overseer.nvim` config wasn't applied, leaving my custom one enabled.

In my custom config, the `name` field was missing from the `register_template` struct, leading to the `overseer.nvim` error.
