### ISSUE TITLE
[Feature] Overseer redirection to ToggleTerm

### ISSUE THREAD

**Issue by chrisvander** [stevearc/overseer.nvim#70]
Excellent plugin so far! Something I'm desiring is redirection of output to a ToggleTerm pane (with shading and such implemented). Since at it's core it's still a built-in terminal window, I figured Overseer could still have tight control over the output. How would I be able to accomplish this? ToggleTerm does some setup, so it isn't as simple as creating an action to swap out the existing terminal buffer that the task is in without losing all of ToggleTerm's wrapping functionality.

**Comment by stevearc** [comment]
Not sure what the internals of toggleterm look like, but this might be possible. The biggest issue I see is that both plugins expect to own the buffer. The most likely route that I see is to make a [custom run strategy](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/strategy/terminal.lua) for overseer that uses [Terminal.new](https://github.com/akinsho/toggleterm.nvim/blob/3ba683827c623affb4d9aa518e97b34db2623093/lua/toggleterm/terminal.lua#L176) instead of `vim.fn.termopen()`. That way toggleterm can "own" all the setup and config, and overseer can plug into the output/exit handlers to get all the information it needs.

**Comment by Oliver-Leete** [comment]
I've been using a custom component to work with ToggleTerm. It's a bit of a hack, and uses a private function of ToggleTerm (so it might break at some point). I'm sure it can be done a lot better by making a custom run strategy, there are probably lots of edge cases where my component won't work as expected.

[Here is the code for the component](https://github.com/Oliver-Leete/Configs/blob/46bd422d87022ed824366475d151440cf0346059/nvim/lua/overseer/component/user/attach_toggleterm.lua) and I have some actions for [attaching](https://github.com/Oliver-Leete/Configs/blob/46bd422d87022ed824366475d151440cf0346059/nvim/lua/user/overseer_config.lua#L81) and [detaching](https://github.com/Oliver-Leete/Configs/blob/46bd422d87022ed824366475d151440cf0346059/nvim/lua/user/overseer_config.lua#L107) ToggleTerm.

Big chunks of the code can be removed, most of it is just for other things in my config, like anything referring to  `OTerm` or `STerm`.

**Comment by stevearc** [comment]
Yeah a strategy might work better for you. I don't have any docs written yet about the custom strategies (because so far there hasn't been a huge need for them), but you can find the type definition in [strategy/init.lua](https://github.com/stevearc/overseer.nvim/blob/93ea08c8a8a3d0a2c03a9e4c04ff1f9b157376f9/lua/overseer/strategy/init.lua#L6-L14) along with the empty "Nil" version. With that as a skeleton and the other examples in that directory it should be straightforward to make something that works with ToggleTerm.

**Comment by chrisvander** [comment]
Awesome. Thanks for the component @Oliver-Leete, I was going down that rabbit hole last night until I realized it would be a lot easier if the buffer was opened in ToggleTerm to begin with. I’ll try out the strategy method and report back…

**Comment by chrisvander** [comment]
```lua
function ToggleTermStrategy:start(task)
  local chan_id
  local mode = vim.api.nvim_get_mode().mode
  local stdout_iter = util.get_stdout_line_iter()

  local function on_stdout(data)
    task:dispatch("on_output", data)
    local lines = stdout_iter(data)
    if not vim.tbl_isempty(lines) then
      task:dispatch("on_output_lines", lines)
    end
  end

  local term = terminal.Terminal:new({
    cwd = task.cwd,
    env = task.env,
    on_create = function(t)
      t:send(task.cmd)
    end,
    on_stdout = function(j, d)
      if self.chan_id ~= j then
        return
      end
      on_stdout(d)
    end,
    on_exit = function(j, c)
      jobs.unregister(j)
      if self.chan_id ~= j then
        return
      end
      log:debug("Task %s exited with code %s", task.name, c)
      -- Feed one last line end to flush the output
      on_stdout({ "" })
      self.chan_id = nil
      -- If we're exiting vim, don't call the on_exit handler
      -- We manually kill processes during VimLeavePre cleanup, and we don't want to trigger user
      -- code because of that
      if vim.v.exiting == vim.NIL then
        task:on_exit(c)
      end
    end,
    hidden = false,
  })

  self.bufnr = term.bufnr

  term:toggle()
  util.hack_around_termopen_autocmd(mode)

  if chan_id == 0 then
    error(string.format("Invalid arguments for task '%s'", task.name))
  elseif chan_id == -1 then
    error(string.format("Command '%s' not executable", vim.inspect(task.cmd)))
  else
    jobs.unregister(chan_id)
    self.chan_id = chan_id
  end
end
```

So far the strategy is working decently, but I see what you mean with needing to own the buffer. I am using `Terminal.new` and it has methods for creating and initializing the buffer in a way that keybindings and theming are respected. Now that I have the buffer, how do I "report back" the inputs/outputs to Overseer? I maintained the same `on_stdout` and `on_exit` functions between `Terminal.new` and the prior vim API method, but Overseer is stuck on pending.

How would I fix it up so Overseer can do outputs and status checks?

**Comment by stevearc** [comment]
The only thing that the strategy needs to provide to the task is the `on_output` and `on_output_lines` events, and it needs to call `task:on_exit()` when the job is completed. The rest of the state management is handled inside task.lua. For example, here is where the task is set to running:
https://github.com/stevearc/overseer.nvim/blob/93ea08c8a8a3d0a2c03a9e4c04ff1f9b157376f9/lua/overseer/task.lua#L623-L629

I would recommend setting the log level to `DEBUG` so you can trace the execution and see where it's failing.
```lua
overseer.setup({
  strategy = "toggleterm",
  log = {
    {
      type = "echo",
      level = vim.log.levels.WARN,
    },
    {
      type = "file",
      filename = "overseer.log",
      level = vim.log.levels.DEBUG,
    },
  },
})
```

You can find the path to the logfile by running `:OverseerInfo`

**Comment by chrisvander** [comment]
Thanks for the help! I missed that I had to make sure to call `term:toggle()` to force ToggleTerm to create the buffer before grabbing the job_id (to set to chan_id) and the buffer number. Also had to check if the `cmd` was coming in as a list and concatenate before passing to ToggleTerm, `Terminal.new({ cmd = cmd })` does not seem to support that format.

My final strategy is [here](https://github.com/chrisvander/dotfiles/blob/main/nvim/lua/overseer/strategy/toggleterm.lua). Works awesome. When I run a task, ToggleTerm pops up with the output down below, and I can use my keybindings to open additional terminals side-by-side or hide it. All the output still goes to Overseer. When the task exits, it disappears from the ToggleTerm view, but the buffer is still around to check for errors in the Overseer pane. Exactly what I wanted!

**Comment by stevearc** [comment]
@chrisvander any interest in submitting a PR? I can think of at least two people that are interested in this functionality :)

**Comment by chrisvander** [comment]
Sure! Opened #72
