### ISSUE TITLE
Custom tags?

### ISSUE THREAD

**Issue by pianocomposer321** [stevearc/overseer.nvim#73]
Would it be possible to add the ability to define custom tags? Or, if not, could the builtin tags at least include more options (e.g. "RUN", "CHECK", etc)?

**Comment by stevearc** [comment]
The tags are just strings, so you can actually already use custom tags! Just use whatever string value you want and it should work as expected.

**Comment by pianocomposer321** [comment]
Ok, thanks, sorry for not checking more thoroughly first! I assumed because it was an `Enum` that using a value not listed there would be an error.

**Comment by stevearc** [comment]
No worries! Tags in general aren't super well documented yet, and that "feature" in particular isn't mentioned at all.
