### ISSUE TITLE
[Question] Restart task if it exists, start if it doesn't

### ISSUE THREAD

**Issue by pianocomposer321** [stevearc/overseer.nvim#75]
Hey, it's me again ;-)

First off, thanks for this plugin, it's literally amazing. As the author of yabs.nvim I can confirm that it's far superior ;-).

So I have a question. Is it possible to have a menu like with `OverseerRun` but then if you select a template for which a task is already in the task list, rather than adding it a second time, restart the task? Otherwise tasks pile up in the task list very frequently, or to avoid it I have to constantly be checking to see if I already started a task from that template.

E.g. I start `cargo run`, then I make a change and want to start it again. Right now I have to remember that I already started one since closing the editor last, or I'll have two `cargo run` tasks in the task list.

Thanks!

**Comment by stevearc** [comment]
Thanks for the kind words! I'm glad overseer is useful for you.

The functionality you're asking for is currently available via the [unique component](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md#unique). You probably don't want to add that to _all_ tasks (though it could be fine; depends on what you're running). You can add it to all of the `cargo *` tasks using this example from the docs: https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#customizing-built-in-tasks

```lua
overseer.add_template_hook({
  module = "^cargo$",
}, function(task_defn, util)
  util.add_component(task_defn, {"unique", replace = false})
end)
```

**Comment by pianocomposer321** [comment]
Very good, that works.

Thanks!
