### ISSUE TITLE
Config to not automatically open task picker when `dap=true` and `postDebugTask=nil`

### ISSUE THREAD

**Issue by ghillb** [stevearc/overseer.nvim#8]
Thank you for this plugin, it is almost too good to be true, when compared to the other task plugins available for neovim :)

My issue is with the `dap = true` feature:
```lua
overseer.setup({
  dap = true,
})
```
For me this always this opens the Overseer task picker, when the debug session is done and no `postDebugTask` is defined in the config:
```lua
dap.configurations.cpp = {
  {
    preLaunchTask = "Compile C++ with gdb flag",
    postDebugTask = nil
  },
```
In many cases this is not needed and can be annoying. It would be nice. if we were able to turn off the automatic task picking, when there is no `postDebugTask` defined in the dap config.

**Comment by stevearc** [comment]
This was just a simple oversight; should be fixed now. Thanks for the report!

**Comment by ghillb** [comment]
Indeed, it is!
