### ISSUE TITLE
better user input for boolean typed parameters?

### ISSUE THREAD

**Issue by emmanueltouzery** [stevearc/overseer.nvim#82]
currently boolean parameters are entered by the user as text:
```lua
  elseif schema.type == "boolean" then
    if string.match(value, "^ye?s?") or string.match(value, "^tr?u?e?") then
      return true, true
    elseif string.match(value, "^no?") or string.match(value, "^fa?l?s?e?") then
      return true, false
    end
  end
```
in lua/overseer/form/utils.lua line 208

I think an ideal rendering for that field type would be more specific to booleans and how they work, like so:

field_name: [ ]
and then:
field_name: [x]
(or maybe even [✓] using unicode)

toggle-able through the space key.

What do you think about this idea?

**Comment by stevearc** [comment]
I do like this idea. I feel like right now the UX for booleans and enums is not as good as I would like. Primarily, though, I want to make sure that it stays intuitive and easy to use. I don't know how I could make "spacebar to toggle" discoverable, especially as I'm trying pretty hard to _not_ override most keybindings so you can edit the buffer like you normally would. The display idea is interesting though. I threw up a quick test in #84, could you take it for a spin and see how it feels?

**Comment by emmanueltouzery** [comment]
i looked at #84. I'm not sure it's progress. It seems to me that it's not easier faster or more intuitive how to flip the option.

since you mention the enum thing... looking at your code, in particular `on_cursor_move`, I feel like the following display ought to be technically possible:
```
boolean_option: [yes] no
```
and then cursor movement would be overridden so that if you move right, the display changes to:
```
boolean_option: yes [no]
```
and so on. so you change the active option by a single horizontal movement. And that way we also prevent invalid states.

and the same code could be reused for enums which have let's say less than 4 members (or similar):
```
enum_option: first [second] third fourth
```
and so if the cursor is on the first option you would say `3l` and you would be moved to the fourth option.

Again, looking at your `on_cursor_move`, I'd guess it's technically possible, but the first question is, do you think it's better than the current setup?

**Comment by emmanueltouzery** [comment]
note that with that idea, maybe bold/underline or colors (including reverse video background/foreground) could be used to highlight the current option, to avoid shifting options by a few characters every time, which could be distracting.

**Comment by stevearc** [comment]
Hmmmm...I agree with both of your points. Both that #84 doesn't feel like progress and that being able to _see_ the options would be very helpful. That's why I implemented the omnifunc and nvim-cmp completion source, but I don't think it works yet for booleans and it's also not guaranteed to show up. Something like what you suggest might be the way to go (at least for enums with a small number of values). That work would be pretty involved and require modifying what is, quite honestly, the messiest and most brittle part of the codebase (the form input logic). I don't think I'll be able to work on this in the near future, but this will go onto the backlog.

Ooo, another fun possibility could be using virtual text to display the options in the line above/below the current. That might be less problematic, since it wouldn't require actually modifying the contents of the buffer.

**Comment by emmanueltouzery** [comment]
Hmm besides displaying the options I'm also concerned about fast input. Virtual text could also contain numbering for instance, eg `1. True 2. False` so you could enter only the number. Well or if only the first letters are enough (which holds at least for booleans), that could do the trick as well without numbers. But then it gets messy if some options have ambiguous beginnings. Ideally we could highlight to the user, maybe through underlining the first few letters, how many characters must be entered.

Eg: _ac_cept _ad_vance

But that again becomes quite involved...

**Comment by emmanueltouzery** [comment]
although if there's a cmp source for completion, that would sort out typing only part of the input! I've not used enums yet with overseer.

**Comment by emmanueltouzery** [comment]
yes, completion now immediately worked for me for booleans! I agree that's much better now, probably good enough to close this issue, at least from my point of view! It's really much nicer. I'll let you decide whether to close it or not. Thank you!

**Comment by stevearc** [comment]
I'll close it for now. We can revisit this if it comes up again in the future
