### ISSUE TITLE
[feature] new input type: password

### ISSUE THREAD

**Issue by emmanueltouzery** [stevearc/overseer.nvim#87]
so i have a task right now for which i'm passing as overseer parameter a password. Ideally there would be a parameter type `password` besides string and others, for which input would be hidden.

I realize that's presumably not trivial... It would be nice though.

**Comment by stevearc** [comment]
Done! Set `conceal = true` on the string parameters and it should hide the values. I defaulted to `concealcursor = nic`, so you can reveal the value by highlighting it in visual mode.

**Comment by emmanueltouzery** [comment]
Amazing, thank you!
