### ISSUE TITLE
[Bug] auto-session integration code

### ISSUE THREAD

**Issue by amar-laksh** [stevearc/overseer.nvim#91]
The integration code for auto-session seems to be buggy.

It saves tasks bundles for the new cwd as well if you change the session while in nvim (for example using: https://github.com/rmagatti/session-lens)

It also keeps showing the old tasks list even when you've changed the session.

The following code fixes the problems:
```lua
-- Convert the cwd to a simple file name
local function get_cwd_as_name()
    local dir = vim.fn.getcwd(0)
    return dir:gsub("[^A-Za-z0-9]", "_")
end

local overseer = require("overseer")
local function are_tasks_for_cwd(tasks)
    local result = true
    for _, task in ipairs(tasks) do
        print(task.cwd, vim.fn.getcwd(0))
        if task.cwd ~= vim.fn.getcwd(0) then
            result = false
            break
        end
    end
    return result
end

local function clear_tasks_list(tasks)
    for _, task in ipairs(tasks) do
        overseer.run_action(task, "dispose")
    end
end

require("auto-session").setup({
    pre_save_cmds = {
        function()
                overseer.save_task_bundle(
                    get_cwd_as_name(),
                    -- Passing nil will use config.opts.save_task_opts. You can call list_tasks() explicitly and
                    -- pass in the results if you want to save specific tasks.
                    nil,
                    { on_conflict = "overwrite" }-- Overwrite existing bundle, if any
                )
        end,
    },
    post_restore_cmds = {
        function()
            -- We load tasks only if they are the correct ones for the cwd
            -- and if not we clear the task list (as it may contain the tasks from the previous session)
            local correct_tasks = are_tasks_for_cwd(overseer.list_tasks({}))
            if correct_tasks then
                overseer.load_task_bundle(get_cwd_as_name(), { ignore_missing = true })
            else
                clear_tasks_list(overseer.list_tasks({}))
            end
        end,
    },
})
```

**Comment by stevearc** [comment]
Ah yes, I forgot how cwd-focused auto-session is. Instead of checking the cwd of the tasks, would it work for you to just clear out previous tasks before opening a session?
```lua
-- Convert the cwd to a simple file name
local function get_cwd_as_name()
  local dir = vim.fn.getcwd(0)
  return dir:gsub("[^A-Za-z0-9]", "_")
end
local overseer = require("overseer")
require("auto-session").setup({
  pre_save_cmds = {
    function()
      overseer.save_task_bundle(
        get_cwd_as_name(),
        -- Passing nil will use config.opts.save_task_opts. You can call list_tasks() explicitly and
        -- pass in the results if you want to save specific tasks.
        nil,
        { on_conflict = "overwrite" } -- Overwrite existing bundle, if any
      )
    end,
  },
  -- Optionally get rid of all previous tasks when restoring a session
  -- THIS IS THE NEW SECTION
  pre_restore_cmds = {
    function()
      for _, task in ipairs(overseer.list_tasks({})) do
        task:dispose(true)
      end
    end
  },
  post_restore_cmds = {
    function()
      overseer.load_task_bundle(get_cwd_as_name(), { ignore_missing = true })
    end,
  },
})
```

**Comment by amar-laksh** [comment]
> Ah yes, I forgot how cwd-focused auto-session is. Instead of checking the cwd of the tasks, would it work for you to just clear out previous tasks before opening a session?
> 
> ```lua
> -- Convert the cwd to a simple file name
> local function get_cwd_as_name()
>   local dir = vim.fn.getcwd(0)
>   return dir:gsub("[^A-Za-z0-9]", "_")
> end
> local overseer = require("overseer")
> require("auto-session").setup({
>   pre_save_cmds = {
>     function()
>       overseer.save_task_bundle(
>         get_cwd_as_name(),
>         -- Passing nil will use config.opts.save_task_opts. You can call list_tasks() explicitly and
>         -- pass in the results if you want to save specific tasks.
>         nil,
>         { on_conflict = "overwrite" } -- Overwrite existing bundle, if any
>       )
>     end,
>   },
>   -- Optionally get rid of all previous tasks when restoring a session
>   -- THIS IS THE NEW SECTION
>   pre_restore_cmds = {
>     function()
>       for _, task in ipairs(overseer.list_tasks({})) do
>         task:dispose(true)
>       end
>     end
>   },
>   post_restore_cmds = {
>     function()
>       overseer.load_task_bundle(get_cwd_as_name(), { ignore_missing = true })
>     end,
>   },
> })
> ```

Yes that seems to work nicely! Sorry didn't look at the available API thoroughly

**Comment by stevearc** [comment]
No worries! I've added it to the documentation
