### ISSUE TITLE
Only override integrated strategy in Neotest

### ISSUE THREAD

**Issue by jfpedroza** [stevearc/overseer.nvim#93]
Currently, Overseer only respects the strategy passed to `run`, but it should respect the default strategy if it's not `integrated`. 

For example, if I change the default strategy for a project, I expect tests to run with that strategy and not with the `overseer` one even if I don't pass it to `run` explicitly.

**Comment by stevearc** [comment]
Consumer should respect the default_strategy now

**Comment by jfpedroza** [comment]
Works properly. Thanks!
