### ISSUE TITLE
[Bug] After loading a task bundle, every included task is automatically run

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/overseer.nvim#95]
As the title says. How could this behaviour be avoided?

I mean, when I load a task bundle, I would like to keep those tasks in a *stopped* state by default.

**Comment by stevearc** [comment]
I've added an option to the API method that will allow you to disable the autostart. If you're using the `OverseerLoadBundle` command, you can get this behavior by adding using a bang: `OverseerLoadBundle!`

**Comment by pidgeon777** [comment]
Great work 👍.

I wonder if there is a way to enable autostart only for certain tasks when loading the bundle.

Maybe by setting an option in the `register_template` struct?

**Comment by stevearc** [comment]
I think this is getting a little too specific. If you want some tasks to autostart and others to not, your best bet is to load the bundle with `autostart = false` and then iterate through the tasks yourself calling start on the ones you want started. If you want to designate it when you register the template, try adding a flag to the metadata of the task that you can read later.

**Comment by pidgeon777** [comment]
> If you want to designate it when you register the template, _try adding a flag to the metadata of the task that you can read later_.

I've not understood that bit, could you kindly clarify, please 🙂.

**Comment by stevearc** [comment]
When you register the template you can make it create a task with some specific metadata

```lua
overseer.register_template({
  name = "Some Task",
  builder = function(params)
    return {
      cmd = {'echo'},
      args = {"hello", "world"},
      metadata = {
        autostart_when_loaded = true,
      },
    }
  end,
})
```

Then after you load a bundle you could run a function like this
```lua
for _, task in ipairs(overseer.list_tasks({status = overseer.STATUS.PENDING})) do
  if task.metadata.autostart_when_loaded then
    task:start()
  end
end
```
