### ISSUE TITLE
[Feature] Specify template directory instead of individual template files

### ISSUE THREAD

**Issue by petobens** [stevearc/overseer.nvim#97]
Hi! Currently in my setup I do:
```lua
overseer.setup({
    templates = {
        'builtin',
        'user.run_arara',
        'user.run_lua',
        'user.run_python',
        'user.run_script',
    },
})
```
I was wondering whether an option could be introduce to specify a user template dir such data the above config could be simplified to something like:
```lua
overseer.setup({
    templates = {
        'builtin',
        'user/*'
    },
})
```
Thanks in advance!

**Comment by stevearc** [comment]
It's a bit of a more manual process, but you could just specify `'user'` if you add a `user/init.lua` file and enumerate all the tasks there. That's how `builtin` works https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/template/builtin.lua

It would be neat to automatically detect files in a directory instead of having to manually specify them, but I don't find myself needing that feature. I would review a pull request for it, though!

**Comment by petobens** [comment]
> It's a bit of a more manual process, but you could just specify 'user' if you add a user/init.lua file and enumerate all the tasks there

I tried that but I'm getting:
```lua
[ERROR] Error loading template 'run_lua': module 'overseer.template.run_lua' not found:
        no field package.preload['overseer.template.run_lua']module overseer.template.run_lua not found
        no file './overseer/template/run_lua.lua'
        no file '/usr/share/luajit-2.1.0-beta3/overseer/template/run_lua.lua'
        no file '/usr/local/share/lua/5.1/overseer/template/run_lua.lua'
        no file '/usr/local/share/lua/5.1/overseer/template/run_lua/init.lua'
        no file '/usr/share/lua/5.1/overseer/template/run_lua.lua'
        no file '/usr/share/lua/5.1/overseer/template/run_lua/init.lua'
        no file './overseer/template/run_lua.so'
        no file '/usr/local/lib/lua/5.1/overseer/template/run_lua.so'
        no file '/usr/lib/lua/5.1/overseer/template/run_lua.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './overseer.so'
        no file '/usr/local/lib/lua/5.1/overseer.so'
        no file '/usr/lib/lua/5.1/overseer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
So it doesn't seem to see my `user/` folder?

**Comment by stevearc** [comment]
So the full module path that it's going to be looking for is `overseer.template.user`, which means you can create a file either at `lua/overseer/template/user/init.lua` or `lua/overseer/template/user.lua`. Have you done that?

**Comment by petobens** [comment]
Using `lua/overseer/template/user.lua` seems to do the trick. Thanks! Feel freet to close if you deem fit
