### ISSUE TITLE
Extrange colorscheme on OverseerRunCm

### ISSUE THREAD

**Issue by groteck** [stevearc/overseer.nvim#98]
I have being trying to change the color scheme by hand but I was not able to do it, I'm using [catppuccin](https://github.com/catppuccin/nvim), so I think it is some other highlight group that is not part of the plugin, maybe you know better and can point me in the right direction.

![image](https://user-images.githubusercontent.com/833030/217515450-8d32872d-f809-4acf-9568-937627d18643.png)

```lua
vim.api.nvim_set_hl(0,⋅"OverseerComponent",⋅{⋅bg⋅=⋅"#ff0000",⋅fg⋅=⋅"#ff0000"⋅})↴
vim.api.nvim_set_hl(0,⋅"OverseerField",⋅{⋅bg⋅=⋅"#ff0000",⋅fg⋅=⋅"#ff0000"⋅})↴
vim.api.nvim_set_hl(0,⋅"OverseerTask",⋅{⋅bg⋅=⋅"#ff0000",⋅fg⋅=⋅"#ff0000"⋅})↴
vim.api.nvim_set_hl(0,⋅"OverseerTaskBorder",⋅{⋅bg⋅=⋅"#ff0000",⋅fg⋅=⋅"#ff0000"⋅})↴
vim.api.nvim_set_hl(0,⋅"OverseerOutput",⋅{⋅bg⋅=⋅"#ff0000",⋅fg⋅=⋅"#ff0000"⋅})↴
```

**Comment by stevearc** [comment]
Could you clarify what elements you're trying to change the color of?
